= Design

Dit ontwerp beschrijft het beoogde gebruiksscenario voor het dataproduct
_Buurtnet_, alsmede de achterliggende architectuur en gemaakte keuzes.

[NOTE]
====
include::partial$data_product.adoc[]
====

== Reikwijdte

Dit dataproduct verstrekt de informatie voor de volgende gebruikersscenario's:

1. Wijkbewoners activeren om hun energie-gebruik en -opwek in balans te brengen op basis van beschikbare data, zodat het trafostation niet uitvalt. Door het aanjagen van zelforganisatie en gedragsverandering hopen we piekbelasting te reduceren en spanningsklachten te verminderen waarmee de wachttijd voor wijkgerichte verzwaring wordt overbrugd.
2. Klanten in kritieke wijken inzicht en handelingsperspectief bieden.

== Functionele eisen

Het dataproduct is onderheving aan functionele eisen: wat het dataproduct moet
*doen*.

.Functionele eisen
[cols="1, 1, 1"]
|===
|Als Rol |Wil ik |Want

|Gebruiker
|De belasting van de transformatoren in de MSR in mijn wijk inzien (24 uren historisch, 24 uren geprognotiseerd en actueel)
|Dan krijg ik inzicht in de momenten van overbelasting en kan ik mijn gedrag daarop kan aanpassen.

|Gebruiker 
|Meldingen van momenten waarop overbelasting wordt verwacht ontvangen
|Dan kan ik mijn gedrag hierop aanpassen en helpen de overbelasting te voorkomen.

|===

== Dataservice

=== Gebruiksscenario

Het volgende gebruiksscenario wordt ondersteund:

.Gebruiksscenario
[d2,svg,theme=4]
----

shape: sequence_diagram

vars: {
  d2-config: {
    pad: 20
  }
}

Gebruiker -> "App Store": "Downloaden app"
"App Store" -> Gebruiker: "Installeren app"
Gebruiker -> "BuurtnetApp": "Aanmelden"

Netbeheerder -> BuurtnetApp: "Capaciteit & belasting"

"Gebruiker vraagt op": {
  Gebruiker -> "BuurtnetApp": "Opvragen capaciteit & belasting"
  "BuurtnetApp" -> Gebruiker: "Capaciteit & belasting"
}

"BuurtnetApp stuurt melding": {
  "BuurtnetApp" -> Gebruiker: "Melding over capaciteit & belasting"
  "BuurtnetApp" -> Gebruiker: "Capaciteit & belasting"
}

Gebruiker -> Gebruiker: "Gedrag aanpassen"

----

1. ...

=== Architectuur

Vanuit architectuurperspectief zijn de volgende keuzes gemaakt:

.Architectuur
[d2,svg,theme=4,scaledwidth=100%]
----

vars: {
  d2-config: {
    pad: 20
  }
}

grid-rows: 5
grid-columns: 4

vertical-gap: 80
horizontal-gap: 160

"Netbeheerder".class: [noun; business]
BuurtnetApp.class: [noun; business]
1.class: empty
2.class: empty

3.class: empty
Extract.class: [verb; business]
Transform.class: [verb; business]
Load.class: [verb; business]

"?".class: [noun; application]
"Data Product".class: [noun; application]
"NBNL Dataportaal".class: [noun; application]
4.class: empty

5.class: empty
"Excel File".class: [artifact; technology]

Extract -> Transform: "triggers"
Transform -> Load: "triggers"
"Data Product" -> "Extract": "serves"
"NBNL Dataportaal" -> "Data Product": "accesses (read)"
BuurtnetApp -> Extract: "assigned to"
"Excel File" -> "Data Product": "realises"
"?" -> "Data Product": "accesses (read)"
"Netbeheerder" -> "?": "assigned to"

legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  business_color: "" {
    style: {
      fill: "#ffffaf"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  business_text: "Business" {
    shape: text
  }
  application_color: "" {
    style: {
      fill: "#afffff"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  application_text: "Application" {
    shape: text
  }
  technology_color: "" {
    style: {
      fill: "#afffaf"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  technology_text: "Technology" {
    shape: text
  }
}

classes: {
  *: {
    style: {
      shadow: true
    }
  }
  empty: {
    label: ""
    style: {
      fill: transparent
      stroke-width: 0
    }
  }
  verb: {
    style: {border-radius: 30}
  }
  noun: {
    style: {border-radius: 4}
  }
  artifact: {shape: page}
  business: {
    style: {
      fill: "#ffffaf"
    }
  }
  application: {
    style: {
      fill: "#afffff"
    }
  }
  technology: {
    style: {
      fill: "#afffaf"
    }
  }
}


----

ToDo: 
* Bespreken wat de technische invulling (inclusief integratiepatroon) van fase 1 moet zijn
* Bespreken wat de technische invulling (inclusief integratiepatroon) van fase 2 moet zijn

== Dataset

De dataset beschrijft ...

=== Volume, variety, veracity, velocity

[NOTE]
====
include::partial$four_v.adoc[]
====

[cols="1, 1"]
|===
|Type |Beschrijving

|Volume
|Midden, < 300MB (ongecomprimeerd)

|Variety
|Gestructureerd

|Veracity
|Midden, de dataset wordt samengesteld uit gegevens voor connectiviteit en aansluitingen. Beiden zijn zeer betrouwbaar, maar de koppeling tussen beiden is minder betrouwbaar

|Velocity
|Midden, minimaal één maal per 24 uur (zie functionele eisen)
|===

== Voorwaarden

Dit dataproduct wordt als _open data_ aangeboden.
Dit dataproduct kan op twee verschillende manieren worden geïmplementeerd: 

1. Als gesloten data. Hierbij wordt een aansluiting direct gekoppeld aan een transformator. Hierdoor is er een directe koppeling tussen invoeding en afname van een specifieke aansluiting en de bijdrage die de aansluiting heeft in de belasting van de transformator. Hiervoor wordt de EAN-code van de aansluiting gecommuniceerd in de dataset. De EAN-code is privacygevoelig.
2. Als open data. Hierbij wordt invoeding en afname geaggregeerd per postcode6 en wordt postcode6 gekoppeld aan een transformator. Hiervoor wordt geen EAN-code gecommuniceerd in de dataset. De gebruiker moet zelf aangeven voor welke postcode6 er capaciteit en belasting gevraagd wordt.

== Beslissingen en aannames

[cols="1, 1"]
|===
|Type |Beschrijving

|Aanname
|BuurtnetApp bestaat uit een frontend en een backend. Datasets worden vanuit de backend van de BuurtnetApp opgehaald bij de netbeheerder

|Aanname
|BuurtnetApp kan onderscheid maken tussen beleidskeuze om trafo boven limiet te belasten versus overbelasting vanuit het ondergelegen net

|Aanname
|Er wordt gekozen voor een open dataproduct. Dit houdt in dat er in dit ontwerp geen rekening wordt gehouden met alle faciliteiten die nodig zijn om een gesloten dataproduct te ontsluiten

|Beslissing
|Er is gekozen voor twee fases. In de eerste fase wordt de data aangeleverd in een Excel-bestand. Voor de tweede fase is er nog niet gekozen voor een integratiepatron

|===
