= Detectie van energie-intensieve apparaten ten behoeve flexoplossingen (DEIA)

Dit ontwerp beschrijft het beoogde gebruiksscenario voor het dataproduct DEIA (_Detectie van energie-intensieve apparaten ten behoeve flexoplossingen_), alsmede haar achterliggende architectuur en de gemaakte keuzes. Het is geschreven vanuit het perspectief van de Regionale Netbeheerder (RNB). Voor de leesbaarheid en voor de begripsvorming wordt soms ook een deel van de context beschreven. 

[NOTE]
====
include::partial$data_product.adoc[]
====

== Reikwijdte

Om het net beter te benutten voor kleinverbruik klanten is slimme sturing van apparaten en/of gedragsverandering nodig. Met name de zogenaamde energie-intensieve apparaten met flexibiliteitspotentie zijn hierbij van belang. Denk hierbij aan zonnepanelen (PV), thuislaadpunten (EV), warmtepompen (WP, ook wel afgekort tot HP (heat pumps)), thuisbatterijen (BESS, Battery Energy Storage System) en apparaten ten behoeve van elektrisch koken (keramische en inductie kookplaten). 

Om deze apparaten slim te kunnen sturen, op basis van toestemming van de klant, hebben dienstverleners inzicht nodig in waar deze energie-intensieve apparaten zich bevinden. Data Scientist teams bij de RNB's werken samen om statistische modellen te maken die dit inzicht kunnen geven.

De epic bestaat uit drie fasen, een pilot fase, een landelijke fase en een data deel fase. Dit is vergelijkbaar met een ontwikkel-, test- en productiefase.

=== Pilot fase

In de pilot fase wordt een jaar lang de verbruiksdata van de slimme meters van 620 medewerkers van de drie grootste RNB's gebruikt om een statistisch model te ontwikkelen en te trainen. Dit model is géén dataproduct.

=== Landelijke fase
In de landelijke fase wordt het statistische model landelijk toegepast op alle aansluitingen waarvoor de _use case_ is link:https://www.netbeheernederland.nl/Goedgekeurde_use_cases[goedgekeurd]. Wellicht gaat er eerst een kleine, regionale testfase aan vooraf. Deze fase resulteert in een tabel met voor elk energie-intensief apparaat (PV, EV, WP, BESS) het geschatte vermogen (in kiloWatt piek (kW(p))) met een bijbehorende betrouwbaarheid (_Confidence Level_ in procenten). Deze tabel wordt periodiek bijgewerkt. Zij is _niet_ per aansluiting, maar geaggreerd op middenspanningsruimte (MS/LS-trafo) niveau:

.Voorbeeld eindresultaat (geaggregeerd op MS/LS-trafo)
[cols= "1, 1, 1, 1, 1, 1, 1, 1, 1"]
|===
|Trafo |PV |Confidence |EV |Confidence |WP |Confidence |BESS |Confidence

|123 |0 |100 |0 |90 |5 |80 |0 |100
|345 |3 |90 |22 |95 |5 |70 |4 |70

Ook hier geldt dat het model géén dataproduct is.

|===

=== Data deel fase
In de data deel fase wordt het dataproduct DEIA gebruikt om het statistische model te ontsluiten naar derden, zoals flexaanbieders, maar ook gemeenten en mogelijk andere overheden. 

== Functionele eisen

Het dataproduct moet voldoen aan functionele eisen; deze vertellen wie ("*Als rol*") welke data ("*Wil ik*") nodig heeft en waarom ("*Want*"). Deze functionele eisen zijn alleen van toepassing op de fase data delen. Dat komt doordat dat de enige fase met een dataproduct is.

.Functionele eisen
[cols="1, 1, 8, 8"]
|===
|ID |Als rol |Wil ik |Want

|{counter:fe} 
|Regionale Netbeheerder (RNB)
|Een uniform overzicht van aansluitingen en het gedrag van invoeding en afname in de tijd
|Ik wil deze informatie laten verrijken zodat er een analyse op uitgevoerd kan worden die met grote zekerheid kan vaststellen of zich achter deze aansluiting een van de volgende vijf apparaattypes bevindt: zonnepanelen (PV), thuislaadpunten (EV), warmtepompen (WP),  thuisbatterijen (BESS) of apparaten tbv elektrisch koken

|{counter:fe} 
|Regionale Netbeheerder (RNB)
|Een uniform overzicht van aansluitingen waarachter zich energie-intensieve apparaten bevinden
|Ik wil de aangeslotene in staat stellen om de verbruiksdata van haar slimme meter, met haar toestemming, te delen met aanbiedingen van flexoplossingen

|{counter:fe} 
|Gemeente
|Een uniform overzicht van het geschatte piekvermogen van energie-intensieve apparaten (PV, EV, WP en BESS) achter een MS/LS-trafo
|Ik wil deze informatie gebruiken voor besluitvorming rondom publieke laadpalen en warmtenetten.

|{counter:fe} 
|Flexaanbieder
|Een uniform overzicht van het geschatte piekvermogen van energie-intensieve apparaten (PV, EV, WP en BESS) achter een MS/LS-trafo
|Ik wil deze aangeslotenen een flexpropositie doen

|===

== Dataservice

=== Pilot fase

In de pilot fase is gekozen voor _federated learning_; elke RNB gebruikt haar eigen data om het statistische model te ontwikkelen.

=== Landelijke fase

In de landelijke fase is er gekozen voor een centraal scenario waarbij de geregistreerde verbruiksdata van de slimme meters centraal beschikbaar wordt gesteld aan de data science teams van de deelnemende RNB's.

=== Data delen fase

In de data delen fase is er gekozen voor een centraal scenario waarbij de data geaggregeerd wordt gedeeld als open dataset

=== Gebruiksscenario

.Gebruiksscenario 
[d2,svg,theme=4]
----

vars: {
  d2-config: {
    pad: 20
  }
}

Scenario: {
  shape: sequence_diagram

  CARM: " \nC-ARM\n "
  DST: "Data Scientist\nTeam\n(DS)"
  RNB: "Regionale\nNetbeheerder\n(RNB)"

  DST -> CARM: 1. Vraag kwartierwaarden op
  CARM -> DST: 2. Lever kwartierwaarden
  Analyse: {
    DST -> DST: 3. Verrijk de kwartierwaarden
    DST -> DST: 4. Maak en train model
  }
  DST -> RNB: 5. Stuur model
}


----

1. Een Data Scientists Team vragen de kwartierwaarden op bij C-ARM
2. C-ARM levert de kwartierwaarden aan de het Data Scientist Team
3. Het Data Scientist Team verrijkt de kwartierwaarden. Bijvoorbeeld met locatie- en meteogegevens
4. Het Data Scientist Team maakt en traint het model
5. Het Data Scientist Team stuurt het model naar de Regionale Netbeheerder

=== Architectuur

Vanuit architectuurperspectief zijn de volgende keuzes gemaakt:

.Architectuur
[d2,svg,theme=4]
----

vars: {
  d2-config: {
    pad: 20
  }
}

grid-rows: 5
grid-columns: 4

vertical-gap: 80
horizontal-gap: 160

"Netbeheerder".class: [noun; business]
1_2.class: empty
"Data Scientist".class: [noun; business]
1_4.class: empty

3_1.class: empty
Extract.class: [verb; business]
Transform.class: [verb; business]
Load.class: [verb; business]

"Slimme Meter Lezer".class: [noun; application]
"Slimme Meter".class: [noun; application]
3_3.class: empty
3_4.class: empty

4_1.class: empty
"C-ARM".class: [artifact; technology]
4_3.class: empty
4_4.class: empty

Extract -> Transform: "triggers"
Transform -> Load: "triggers"
"Slimme Meter" -> "Extract": "serves"
"Data Scientist" -> Extract: "assigned to"
"Data Scientist" -> Load: "assigned to"
"C-ARM" -> "Slimme Meter": "realises"
"Slimme Meter Lezer" -> "Slimme Meter": "accesses (read)"
"Netbeheerder" -> "Slimme Meter Lezer": "assigned to"

legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  business_color: "" {
    style: {
      fill: "#ffffaf"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  business_text: "Business" {
    shape: text
  }
  application_color: "" {
    style: {
      fill: "#afffff"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  application_text: "Application" {
    shape: text
  }
  technology_color: "" {
    style: {
      fill: "#afffaf"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  technology_text: "Technology" {
    shape: text
  }
}

classes: {
  *: {
    style: {
      shadow: true
    }
  }
  empty: {
    label: ""
    style: {
      fill: transparent
      stroke-width: 0
    }
  }
  verb: {
    style: {border-radius: 30}
  }
  noun: {
    style: {border-radius: 4}
  }
  artifact: {shape: page}
  business: {
    style: {
      fill: "#ffffaf"
    }
  }
  application: {
    style: {
      fill: "#afffff"
    }
  }
  technology: {
    style: {
      fill: "#afffaf"
    }
  }
}

----


1. De structuur van de dataset is gebaseerd op het _Begrippenmodel NBNL_ en het _Common Information Model_

== Dataset

=== Volume, variety, veracity, velocity

[NOTE]
====
include::partial$four_v.adoc[]
====

==== Dataset

[cols="1, 3"]
|===
|Type |Beschrijving

|Volume
|Laag, < 100MB (ongecomprimeerd)

|Variety
|Gestructureerd

|Veracity
|Hoog

|Velocity
|Laag (15 minuten)
|===

== Voorwaarden

Dit dataproduct wordt als _gesloten data_ aangeboden, onder de grondslag _Grondslag Toestemming_. De grondslag is vereist indien een derde de aanvraag doet, voor een medewerker is toestemming niet vereist indien het om meetdata van de eigen aansluiting(en) gaat.

== Beslissingen en aannames

[cols="1, 3, 6"]
|===
|ID |Type |Beschrijving

|{counter:bea} 
|Aanname
|Het is mogelijk om de data uit het dataproduct te verrijken met gegevens die relevant zin voor de analyse zoals weergegevens

|{counter:bea} 
|Aanname
|Het is mogelijk op basis van analyse te bepalen of één van de vier apparaattypes (zonnepaneel, thuislaadpunt, warmtepomp of thuisbatterij) zich achter het aansluitpunt bevindt.

|{counter:bea} 
|Aanname
|Het is mogelijk om middels een enquête 1.000 medewerkers bij de drie grootste RNB's te vinden die willen meedoen

|{counter:bea} 
|Beslissing
|Zowel in de pilot fase als in de landelijke fase is er behoefte aan 15 minuten waarden (kwartierstanden)

|{counter:bea} 
|Aanname
|In de pilot foas wordt de data verkregen door het periodiek en rechtstreeks uitlezen van de slimme meter, niet door het opvragen van reeds uitgelezen en opgeslagen slimme metersstanden

|{counter:bea} 
|Aanname
|De Data Scientist verrijkt zelf de slimme meter data

|{counter:bea} 
|Aanname
|De Data Scientist berekent niet het gebruiksprofiel van een energie-intensief apparaat

|{counter:bea} 
|Beslissing
|In de landelijke fase komen de kwartierwaarden uit een database

|{counter:bea} 
|Beslissing
|Enexis, Stedin en Alliander hebben elk hun eigen team met Data Scientists

|{counter:bea} 
|Aanname
|Enexis, Steden en Alliander zijn de enige deelnemende RNB's

|{counter:bea} 
|Beslissing
|Elk Data Scientist team krijgt dezelfde data

|{counter:bea} 
|Aanname
|In de pilot fase ontvangt elke Data Scientist team van elke deelnemende RNB de verbruiksdata van de slimme meter van deze RNB en deelt deze met de Data Scientist teams van de andere deelenmende RNB's

|{counter:bea} 
|Beslissing
|Voor elk apparaattype is er een Data Scientist team dat een model maak om haar aanwezigheid te voorspellen inclusief hun geschatte vermogen

|{counter:bea} 
|Beslissing
|Elk Data Scientist team maakt een eigen model om de aanwezigheid één of meerdere apparaattypes te voorspellen inclusief hun geschatte vermogen

|{counter:bea} 
|Beslissing
|De Data Scientist teams verrijken de kwartierwaarden met locatiegegevens (PC6 danwel MS/LS-trafo)

|{counter:bea} 
|Aanname
|Aggregatie in de landelijke fase gebeurt op connectiviteit (je wilt netburen aggregeren)

|===
