= Detectie van energie-intensieve apparaten ten behoeve flexoplossingen

Dit ontwerp beschrijft het beoogde gebruiksscenario voor het dataproduct _energie-intensieve apparaten_, haar achterliggende architectuur en de gemaakte keuzes. 

[NOTE]
====
include::partial$data_product.adoc[]
====

== Reikwijdte

Om het net beter te benutten voor kleinverbruik klanten is slimme sturing van apparaten en/of gedragsverandering nodig. Met name de zogenaamde energie-intensieve apparaten met flexibiliteitspotentie (zoals: zonnepanelen, thuislaadpunten, warmtepompen en thuisbatterijen) zijn hierbij van belang. 

Om deze apparaten slim te kunnen sturen, op basis van toestemming van de klant, hebben dienstverleners inzicht nodig in waar deze energie-intensieve apparaten zich bevinden. 

Dit dataproduct draagt bij aan de detectie van energie-intensieve apparaten. Van deze apparaten bevat het het aansluitingsniveau (1x10A, 1x25A, 3x25A, ...) en vermogen.

== Functionele eisen

Het dataproduct moet voldoen aan functionele eisen; deze vertellen wie ("*Als rol*") welke data ("*Wil ik*") nodig heeft en waarom ("*Want*").

.Functionele eisen
[cols="1, 1, 1"]
|===
|Als rol |Wil ik |Want

|Regionale Netbeheerder (RNB)
|Een uniform overzicht van aansluitingen en het gedrag van invoeding en afname in de tijd
|Ik wil deze informatie laten verrijken zodat er een analyse op uitgevoerd kan worden die met grote zekerheid kan vaststellen of zich achter deze aansluiting een van de volgende vier apparaten bevindt: zonnepanelen (PV), thuislaadpunten (EV), warmtepompen (WP) of thuisbatterijen (BESS)

|Regionale Netbeheerder (RNB)
|Een uniform overzicht van aansluitingen waarachter zich energie-intensieve apparaten bevinden
|Ik wil de aangeslotene een flexoplossing bieden waardoor het net beter benut wordt

|===

== Dataservice

Er is gekozen voor een decentraal scenario waarbij een jaar lang de slimme meters van 1.000 medewerkers van de drie grootste RNB's worden uitgelezen. Dit uitlezen gebeurt per RNB (vandaar decentraal).

=== Gebruiksscenario

.Gebruiksscenario 
[d2,svg,theme=4]
----

vars: {
  d2-config: {
    pad: 20
  }
}

Decentraal scenario: {
	shape: sequence_diagram
	RNB: "Regionale\nNetbeheerder\n(RNB)"
  	MDW: "Medewerker\nRNB\n(MDW)"

  	RNB <-> MDW: 1. Lees slimme meter uit
}

----

 1. Een RNB leest de slimme meter van een deelnemende medewerker uit

=== Architectuur

Vanuit architectuurperspectief zijn de volgende keuzes gemaakt:

.Architectuur
[d2,svg,theme=4]
----

vars: {
  d2-config: {
    pad: 20
  }
}

grid-rows: 5
grid-columns: 4

vertical-gap: 80
horizontal-gap: 160

"Netbeheerder".class: [noun; business]
Consumer.class: [noun; business]
1.class: empty
2.class: empty

3.class: empty
Extract.class: [verb; business]
Transform.class: [verb; business]
Load.class: [verb; business]

"HTTP Server".class: [noun; application]
"Data Product".class: [noun; application]
"NBNL Dataportaal".class: [noun; application]
4.class: empty

5.class: empty
"JSON File".class: [artifact; technology]

Extract -> Transform: "triggers"
Transform -> Load: "triggers"
"Data Product" -> "Extract": "serves"
"NBNL Dataportaal" -> "Data Product": "accesses (read)"
Consumer -> Extract: "assigned to"
"JSON File" -> "Data Product": "realises"
"HTTP Server" -> "Data Product": "accesses (read)"
"Netbeheerder" -> "HTTP Server": "assigned to"

legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  business_color: "" {
    style: {
      fill: "#ffffaf"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  business_text: "Business" {
    shape: text
  }
  application_color: "" {
    style: {
      fill: "#afffff"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  application_text: "Application" {
    shape: text
  }
  technology_color: "" {
    style: {
      fill: "#afffaf"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  technology_text: "Technology" {
    shape: text
  }
}

classes: {
  *: {
    style: {
      shadow: true
    }
  }
  empty: {
    label: ""
    style: {
      fill: transparent
      stroke-width: 0
    }
  }
  verb: {
    style: {border-radius: 30}
  }
  noun: {
    style: {border-radius: 4}
  }
  artifact: {shape: page}
  business: {
    style: {
      fill: "#ffffaf"
    }
  }
  application: {
    style: {
      fill: "#afffff"
    }
  }
  technology: {
    style: {
      fill: "#afffaf"
    }
  }
}

----


1. De structuur van de dataset is gebaseerd op het _Begrippenmodel NBNL_ en het _Common Information Model_
2. Aanlevering van de klantcontactgegevens en de aangeslotenegegevens geschiedt via JSON-bestanden

== Dataset

=== Volume, variety, veracity, velocity

[NOTE]
====
include::partial$four_v.adoc[]
====

==== Dataset

[cols="1, 3"]
|===
|Type |Beschrijving

|Volume
|Laag, < 100MB (ongecomprimeerd)

|Variety
|Gestructureerd

|Veracity
|Hoog

|Velocity
|Laag (15 minuten)
|===

== Voorwaarden

Dit dataproduct wordt als _gesloten data_ aangeboden, onder de grondslag _Grondslag Toestemming_. De grondslag is vereist indien een derde de aanvraag doet, voor een medewerker is toestemming niet vereist indien het om meetdata van de eigen aansluiting(en) gaat.

== Beslissingen en aannames

[cols="1, 1"]
|===
|Type |Beschrijving

|Aanname
|Het is mogelijk om de data uit het dataproduct te verrrijken met gegevens die relevant zin voor de analyse zoals weergegevens

|Aanname
|Het is mogelijk op basis van analyse te bepalen of één van de vier apparaattypes (zonnepaneel, thuislaadpunt, warmtepomp of thuisbatterij) zich achter het aansluitpunt bevindt.

|Aanname
|Het is mogelijk om middels een enquête 1.000 medewerkers bij de drie grootste RNB's te vinden die willen meedoen

|Aanname
|Er is behoefte aan 15 minuten waarden

|Aanname
|De data wordt verkregen door het periodiek en rechtstreeks uitlezen van de slimme meter, niet door het opvragen van reeds uitgelezen en opgeslagen slimme metersstanden

|===
