= Energieprofielen

Dit ontwerp beschrijft het beoogde gebruiksscenario voor het dataproduct _Energieprofielen_, alsmede de achterliggende architectuur en gemaakte keuzes. 

[NOTE]
====
include::partial$data_product.adoc[]

====

== Reikwijdte

Het doel is een open dataset van profielen die per gebeid gegroepeerd kunnen worden. Deze gebieden zijn GV (grootverbruik), KV (kleinverbruik) en SBI (de standaard bedrijfsindeling van de het CBS op basis van de KvK).
De prioriteit van de profielen is: Eerst GV (grootverbruik) dan KV (kleinverbruik) en tot slot SBI (de standaard bedrijfsindeling van de het CBS op bais van de KvK).

// Bron: Mail, Robbert Hardin, Aantekeningen Afstemmen gebiedsprofielen, di 18-11-2025 11:09

== Rollen

Het dataproduct beschreven in dit ontwerp kent meerdere stakeholders, elk met een eigen verzameling behoeften en wensen. 

.Rollen
[cols="1, 2"]
|===
|Rol |Beschrijving

|Ingenieursbureau
|Een ingenieursbureau is een bedrijf dat diensten levert op het gebied van advisering, ontwerp en begeleiding voor technische projecten binnen uiteenlopende sectoren.

// Bron: https://nl.wikipedia.org/wiki/Ingenieursbureau

|NP RES
|NP RES staat voor het Nationaal Programma Regionale Energie Strategie. Provincies, gemeenten, waterschappen en netbeheerders werken in dertig regio’s samen met de samenleving aan het grootschalig opwekken van duurzame elektriciteit op land met windturbines en zonnepanelen. Ook stemmen ze warmtevraag en -aanbod op elkaar af.

// Bron: https://www.netbeheernederland.nl/artikelen/nieuws/np-res-doelstellingen-waar-staan-we-eind-2024

|Woningcorporatie
|Een woningcorporatie is een sociale woningbouworganisatie die zich richt op het bouwen, beheren en verhuren van woonruimte met een betaalbare huur.

// Bron: https://rws.begrippenxl.nl/ABDL/nl/page/DEF-5338

|KGG
|Ministerie van Klimaat en Groene Groei.

// Bron: https://www.rijksoverheid.nl/ministeries/ministerie-van-klimaat-en-groene-groei

|Provincies en gemeentes
|Deelgebieden met een eigen regionaal bestuur. Zij voeren landelijk en eigen beleid uit. Staatsrechtelijk is de provincie de bestuurlijke eenheid tussen de gemeenten en de rijksoverheid.

// Bron: https://nl.wikipedia.org/wiki/Provincie, https://www.rijksoverheid.nl/onderwerpen/provincies/taken-provincie, https://www.rijksoverheid.nl/onderwerpen/gemeenten/taken-gemeente

|===

== Functionele eisen

Het dataproduct moet voldoen aan functionele eisen; deze vertellen wie (*"Als rol"*) welke data (*"Wil ik"*) nodig heeft en waarom (*"Want"*).

.Functionele eisen
[cols="1, 1, 3, 3"]
|===
|ID |Als Rol |Wil ik |Want

|{counter:fe}
|Ingenieursbureau
|Ik wil meer inzicht krijgen in energieverbruik in bepaalde buurten/gebieden
|Ik wil betere technisch-economische haalbaarheidsanalyses van duurzame lokale energiesystemen kunnen uitvoeren 

// Bron: ADA-E1026 - Energiedata KleinVerbruik-071025-072013.pdf, pagina 2

|{counter:fe}
|NP RES
|Ik wil energiesprofielen gegroepeerd per gebied
|Ik wil vraag en aanbod van energie afstemmen met een gebiedsgerichte aanpak

// Bron: ADA-E1026 - Energiedata KleinVerbruik-071025-072013.pdf, pagina 2

|{counter:fe}
|Woningcorporatie
|Ik wil meer inzicht in energieverbruik van mijn woningportfolio
|Ik wil betere prioriteiten stellen met betrekking tot het verduurzamen van mijn woningportfolio

// Bron: ADA-E1026 - Energiedata KleinVerbruik-071025-072013.pdf, pagina 2

|{counter:fe}
|KGG
|Ik wil inzicht in energieverbruik op nationaal en regionaal niveau
|Ik wil beleid voeren en de voortgang van de energietransitie monitoren

// Bron: ADA-E1026 - Energiedata KleinVerbruik-071025-072013.pdf, pagina 3

|{counter:fe}
|Provincies en gemeentes
|Ik wil energieprofielen
|Ik wil de energietransitie monitoren, prioriteiten stellen en focus aanbrengen

// Bron: ADA-E1026 - Energiedata KleinVerbruik-071025-072013.pdf, pagina 3

|===

== Dataservice

=== Gebruiksscenario

Het volgende gebruiksscenario wordt ondersteund:

.Gebruiksscenario
[d2,svg,theme=4]
----
shape: sequence_diagram

vars: {
  d2-config: {
    pad: 20
  }
}

"Rol: Rol

----

1. Rol

=== Architectuur

Vanuit architectuurperspectief zijn de volgende keuzes gemaakt:

.Architectuur
[d2,svg,theme=4,scaledwidth=100%]
----
vars: {
  d2-config: {
    pad: 20
  }
}

grid-rows: 5
grid-columns: 4

vertical-gap: 80
horizontal-gap: 160



legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  business_color: "" {
    style: {
      fill: "#ffffaf"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  business_text: "Business" {
    shape: text
  }
  application_color: "" {
    style: {
      fill: "#afffff"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  application_text: "Application" {
    shape: text
  }
  technology_color: "" {
    style: {
      fill: "#afffaf"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  technology_text: "Technology" {
    shape: text
  }
}

classes: {
  *: {
    style: {
      shadow: true
    }
  }
  empty: {
    label: ""
    style: {
      fill: transparent
      stroke-width: 0
    }
  }
  verb: {
    style: {border-radius: 30}
  }
  noun: {
    style: {border-radius: 4}
  }
  artifact: {shape: page}
  business: {
    style: {
      fill: "#ffffaf"
    }
  }
  application: {
    style: {
      fill: "#afffff"
    }
  }
  technology: {
    style: {
      fill: "#afffaf"
    }
  }
}

----

== Dataset

De dataset beschrijft per gebied (postcode, SBI) en per gebruik (KV, GV) de profielen.

=== Volume, variety, veracity, velocity

[NOTE]
====
include::partial$four_v.adoc[]
====

[cols="1, 1"]
|===
|Type |Beschrijving

|Volume
|Laag

|Variety
|Gestructureerd

|Veracity
|Midden

|Velocity
|Laag

|===

== Voorwaarden
Dit dataproduct wordt als open/gesloten data aangeboden, onder de volgende grondslag(en) 

De lijst van grondslagen is te vinden op: https://www.autoriteitpersoonsgegevens.nl/themas/basis-avg/avg-algemeen/grondslagen-avg-uitgelegd.

De grondslagen zijn:

- Toestemming

- Overeenkomst

- Wettelijke verplichting

- Vitaal belang

- Taak van algemeen belang of uitoefening van openbaar gezag

- Gerechtvaardigd belang

== Beslissingen en aannames

[cols="1, 3, 6"]
|===
|Id |Type |Beschrijving

|{counter:bea} |Aanname |Het wordt één dataproduct dat alledrie de profielen (KV, GV en SBI) kan bevatten.

|{counter:bea} |Aanname |Per gebied wordt het één dataproduct

|{counter:bea} |Aanname |Groepering op postcode gaat op PC4 of PC5

|{counter:bea} |Aanname |De datasets horende bij de dataproducten worden open datasets met in achtneming van herleidbaarheid 

// Bron: 

|===

== Interpretaties

In dit ontwerp worden een aantal begrippen gebruikt die ambigu zijn waardoor ze verkeerd geïnterpreteerd kunnen worden. Daarom volgt hier hun interpretatie (hoe ze bedoeld zijn). Dit zijn dus _géén_ definities.
