= Netburen

Dit ontwerp beschrijft het beoogde gebruiksscenario voor het dataproduct
_Groengascapaciteitskaart_, alsmede de achterliggende architectuur en gemaakte keuzes.

[NOTE]
====
include::partial$data_product.adoc[]
====

== Reikwijdte

Het doel van de oplossing is het ondersteunen van de verkennende fase van het
vormen van een Energiehub. Bijbehorende dataproducten zijn mogelijk breder
inzetbaar, zoals voor andere toepassingen of de ontwerpende fase van een
Energiehub, maar deze toepassingen zijn niet in scope voor dit dataproduct.

.Rollen
[cols="1, 2"]
|===
|Rol |Beschrijving

|Netbeheerder
|

|GV-klant
|

|Technisch adviseur
|

|Marktpartij
|

|===


== Functionele eisen

De dataproducten zijn onderheving aan functionele eisen: de informatievraag die
de dataproducten en onderliggende oplossing moeten beantwoorden.

.Functionele eisen
[cols="1, 1, 3, 3"]
|===
|ID |Als Rol |Wil ik |Want

|{counter:fr}
|Netbeheerder
|Enkel inzicht verstrekken vanuit *use case*-perspectief.
|Ik moet voldoen aan beleid rondom het communiceren van nettopologie van de
 netbeheerder.

|{counter:fr}
|Technisch adviseur
|Inzicht in de aansluitingen die samen een (potentiële) Energiehub kunnen
 vormen.
|ik wil inzicht in welke GV-klanten te benaderen.

|{counter:fr}
|Technisch adviseur
|Inzicht in netburen en historische verbruiksgegevens (kwartierwaardes) van de
 potentiële deelnemers aan de Energiehub.
|Ondersteunen bij het _optimaliseren achter de meter_.

|{counter:fr}
|Marktpartij
|Inzicht in nettopologie van netstation tot aan individueel aangesloten
 GV-klant (_aansluiting_).
|Ik wil inzicht in hoe relevante netfuncties invloed op elkaar uitoefenen.

|{counter:fr}
|Marktpartij
|Inzicht in de capaciteit en restcapaciteit (vrije ruimte) op veldniveau en
secundaire zijde(s) van de relevante transformatoren, als _operationele limiet_.
|#TODO: ?#

|{counter:fr}
|Technisch adviseur
|Inzicht in de belasting op veldniveau en secundaire zijde(s) van de relevante
 transformatoren; 2 jaar historische kwartierwaardes (gemeten) voor invoeding &
 afname (gesplitst).
|#TODO: ?#

|{counter:fr}
|Technisch adviseur
|GV-klanten ondersteunen bij het opzetten van een GTO.
|#TODO: ?#

|{counter:fr}
|Technisch adviseur
|Inzicht in de gelijktijdige kWmax (piek)
|Input voor het opzetten van GTO

|===

== Dataservice

=== Gebruiksscenario

Het volgende gebruiksscenario wordt ondersteund:

.Gebruiksscenario
[d2,svg,theme=4]
----
shape: sequence_diagram

vars: {
  d2-config: {
    pad: 20
  }
}

----

1. ...

=== Architectuur

Vanuit architectuurperspectief zijn de volgende keuzes gemaakt:

.Architectuur
[d2,svg,theme=4,scaledwidth=100%]
----
vars: {
  d2-config: {
    pad: 20
  }
}

grid-rows: 5
grid-columns: 4

vertical-gap: 80
horizontal-gap: 160

"Netbeheerder".class: [noun; business]
Consumer.class: [noun; business]
1.class: empty
2.class: empty

3.class: empty
Extract.class: [verb; business]
Transform.class: [verb; business]
Load.class: [verb; business]

"HTTP Server".class: [noun; application]
"Data Product".class: [noun; application]
"NBNL Dataportaal".class: [noun; application]
4.class: empty

5.class: empty
"JSON File".class: [artifact; technology]

Extract -> Transform: "triggers"
Transform -> Load: "triggers"
"Data Product" -> "Extract": "serves"
"NBNL Dataportaal" -> "Data Product": "accesses (read)"
Consumer -> Extract: "assigned to"
"JSON File" -> "Data Product": "realises"
"HTTP Server" -> "Data Product": "accesses (read)"
"Netbeheerder" -> "HTTP Server": "assigned to"

legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  business_color: "" {
    style: {
      fill: "#ffffaf"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  business_text: "Business" {
    shape: text
  }
  application_color: "" {
    style: {
      fill: "#afffff"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  application_text: "Application" {
    shape: text
  }
  technology_color: "" {
    style: {
      fill: "#afffaf"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  technology_text: "Technology" {
    shape: text
  }
}

classes: {
  *: {
    style: {
      shadow: true
    }
  }
  empty: {
    label: ""
    style: {
      fill: transparent
      stroke-width: 0
    }
  }
  verb: {
    style: {border-radius: 30}
  }
  noun: {
    style: {border-radius: 4}
  }
  artifact: {shape: page}
  business: {
    style: {
      fill: "#ffffaf"
    }
  }
  application: {
    style: {
      fill: "#afffff"
    }
  }
  technology: {
    style: {
      fill: "#afffaf"
    }
  }
}

----

* ...

== Dataset

De dataset beschrijft ...

=== Volume, variety, veracity, velocity

[NOTE]
====
include::partial$four_v.adoc[]
====

[cols="1, 1"]
|===
|Type |Beschrijving

|Volume
|Laag, < 100MB (ongecomprimeerd)

|Variety
|Gestructureerd

|Veracity
|Medium, ...

|Velocity
|Laag, ...
|===

== Voorwaarden

Dit dataproduct wordt als _gesloten data_ aangeboden, onder de grondslag ...

== Beslissingen en aannames

[cols="1, 1"]
|===
|Type |Beschrijving

|Aanname
|De oplossing heeft als reikwijdte *enkel* het ondersteunen van de verkennende
 fase van een Energiehub.

|Aanname
|Lokale overheden zijn geen stakeholders binnen deze oplossing.

|Aanname
|Energiehubregisseur is onderdeel van de rol van Technisch adviseur.

|Aanname
|Het proces behorende bij _optimaliseren achter de meter_ ligt in het domein
 van de Technisch adviseur en is daarmee out-of-scope voor het ontwerp.

|Aanname
|Het combineren van datasets levert mogelijk meer informatie ...

|Beslissing
|Kabelinformatie is out-of-scope voor het ontwerp.

|Aanname
|Voor nettopologie wordt uitgegaan van de normaalstand van het net.

|Aanname
|Meetgegevens voor veld en transformator zijn enkel geldig binnen de
 normaalstand. Indien de normaalstand gewijzigd is binnen de historische periode
 zijn de meetwaardes gedaan voor de wijziging niet geldig en worden *niet*
 gecommuniceerd.

|Aanname
|Er worden geen geocoördinaten in het informatiemodel opgenomen.

|Aanname
|Er wordt geen informatie gecommuniceerd over netbeveiliging, _n-1_ wordt
geabstraheerd als onderdeel van de nettopologie.

|Aanname
|Er wordt geen informatie gecommuniceerd over wachtrijen en kortsluitstromen.

|Aanname
|Belasting wordt voor de afgelopen twee jaar in kwartierwaardes gecommuniceerd,
 capaciteit wordt op basis van een enkele operationele limiet gecommuniceerd.

|===
