= Netcode Elektriciteit H13

Dit ontwerp beschrijft het beoogde gebruiksscenario voor het dataproducten
behorende bij de implementatie van
https://wetten.overheid.nl/BWBR0037940/2025-05-08#Hoofdstuk13[Netcode
Elektriciteit Hoofdstuk 13], alsmede de achterliggende architectuur en gemaakte
keuzes.

[NOTE]
====
include::partial$data_product.adoc[]
====

== Reikwijdte

Vanuit het kernteam Netdigitalisering is opdracht gegeven voor de start van de
eerste fase van de projectopdracht. Een eerste deel focust op het leggen van de
definities voor de samenwerking:

* hoe gaan we de uitwisseling vormgeven?
* standaardisering van de attribuutdefinities;
* opstellen informatiemodellen;
* identificatie van assets in elkaars net;
* wat gaan we uitwisselen?
* onderzoeken beschikbaarheid data binnen de organisatie van de DSO en TSO
zoals beschreven in Netcode 13.

Het op te leveren product is een informatiemodel ten behoeve van de
uitwisseling van structurele asset data tussen de netbeheerders. Deze dient op
zo'n manier vorm te zijn gegeven dat zij de basis vormt voor de tweede fase
waarin de uitwisseling verder wordt vormgegeven.

== Rollen

De dataproducten beschreven in dit ontwerp kennen meerdere stakeholders, elk
met een eigen verzameling behoeften en wensen. De <<_functionele_eisen>>
behorend bij elke rol worden in het volgende hoofdstuk beschreven.

#TODO: beheerder gesloten distributiesysteem?#

.Rollen
[cols="1, 2"]
|===
|Rol |Beschrijving

|Landelijke Netbeheerder (LNB)
|

|Regionale Netbeheerder (RNB)
|

|Toezichthouder
|
|===

== Functionele eisen

De dataproducten zijn onderheving aan functionele eisen: de informatievraag die
de dataproducten en onderliggende oplossing moeten beantwoorden. Daar waar van
toepassing zijn functionele eisen gerelateerd aan de
https://wetten.overheid.nl/BWBR0037940/2025-05-08#Hoofdstuk13[Netcode
Elektriciteit].

.Functionele eisen
[cols="1, 1, 3, 3, 2"]
|===
|ID |Als Rol |Wil ik |Want |NC13

|{counter:fr}
|LNB
|Inzicht in de structurele gegevens van elk afzonderlijk station van de RNB dat
 direct gekoppeld is aan het landelijk hoogspanningsnet
|
|§13.5.1, §13.5.2

|{counter:fr}
|LNB
|Inzicht in de structurele gegevens van elk achter een overdrachtspunt van een
 aansluiting gelegen deelnet van de RNB
|
|§13.5.3, §13.5.4

|{counter:fr}
|LNB
|Inzicht in de structurele gegevens van elk achter een overdrachtspunt van een
 aansluiting gelegen deelnet van elke beheerder van een _gesloten
 distributiesysteem_ aangesloten op het landelijk hoogspanningsnet
|
|§13.5.5

|===

== Dataset

De oplossing voor de implementatie van Netcode H13 bestaat uit het
implementeren van meerdere dataproducten voor o.a. connectiviteit,
netelementinformatie en de stabiele toestand van het elektriciteitsnet.

[NOTE]
====
Vanuit _Netbeheer Nederland_ is gekozen voor standaardisatie van de
data-uitwisseling op basis van het _Common Information Model_ (CIM). Het CIM is
een verzameling internationale standaarden die samen een informatiemodel vormen
voor het beschrijven van het elektriciteitsnet.

Als beginpunt van het beschrijven van de dataproducten is er gekozen voor de
_Common Grid Model Exchange Standard_ (CGMES). CGMES is een verzameling
*profielen* (dataproducten) die meerdere gebruiksscenario's beschrijven,
specifiek voor Transmission System Operators (TSO). De CGMES is daarmee een
specialisatie van het CIM, maar niet volledig toepasbaar voor het beschrijven
van het elektriciteitsnet van de regionale netbeheerder.

De in deze oplossing beschreven dataproducten worden om die reden aangevuld
vanuit het CIM, daar waar CGMES een functioneel gevraagd gebruiksscenario niet
ondersteunt.
====

Er zijn vijf verschillende profielen (dataproducten met bijbehorende datasets)
nodig om de informatievraag in te vullen:

.Profielen
[cols="1, 2"]
|===
|Profiel |Beschrijving

|Equipment (EQ)
|Eigenschappen van *netfuncties*, de connectiviteit van het
 elektriciteitsnet

|Operation (OP)
|Operationele meetwaarden, discreet en analoog. Meetwaarden zijn gemeten,
 berekend of geschat.

|Steady State Hypothesis (SSH)
|Stabiele toestand van het elektriciteitsnet

|Asset (AS)
|Fysieke eigenschappen van *netelementen*

|Market (MKT)
|Marktfacilitering binnen EU-markten
|===

=== Volume, variety, veracity, velocity

[NOTE]
====
include::partial$four_v.adoc[]
====

Voor alle vijf de profielen gelden dezelfde kenmerken:

[cols="1, 1"]
|===
|Type |Beschrijving

|Volume
|Laag, < 100MB (ongecomprimeerd)

|Variety
|Gestructureerd

|Veracity
|Medium, de gegevens zijn bij elke netbeheerder beschikbaar, maar niet elke
 netbeheerder heeft de volledige dataset tot haar beschikking.

|Velocity
|Laag, #TODO: hoe vaak worden de datasets uitgewisseld? Maandelijke, kwartaal,
 jaarlijks?#
|===

== Dataservice

=== Gebruiksscenario

Het volgende gebruiksscenario wordt ondersteund:

.Gebruiksscenario
[d2,svg,theme=4]
----
vars: {
  d2-config: {
    pad: 20
  }
}

shape: sequence_diagram

Landelijke\nNetbeheerder -> Landelijke\nNetbeheerder: "1. Verzamel gegevens"
Landelijke\nNetbeheerder -> Regionale\nNetbeheerder: "2. Lever Equipment Profile"

Regionale\nNetbeheerder -> Regionale\nNetbeheerder: "3. Verwerk koppelpunten"
Regionale\nNetbeheerder -> Landelijke\nNetbeheerder: "4. Lever Equipment Profile"
----

1.
2.
3.
4.

=== Kwaliteitseisen

Kwaliteitseisen (_non functionals_) beschrijven wat een oplossing moet *zijn*.
Voor dit ontwerp wordt de categorisering vanuit _ISO/IEC 25010_ aangehouden,
waar van toepassing.

.Kwaliteitseisen
[cols="1, 1, 1"]
|===
|Categorie |Beschrijving |Kwaliteitseisen

 |Prestaties
 |Snel en efficiënt functioneren, met minimale laadtijden en schaalbaar
a|

 |Overdraagbaarheid
 |Eenvoudig te verplaatsen of te migreren naar een andere omgeving
a|

 |Gebruiksvriendelijkheid
 |Intuïtief en makkelijk te gebruiken voor de eindgebruiker
a|

 |Betrouwbaarheid
 |Stabiel en foutbestendig, met een hoge beschikbaarheid
a|* integriteit -> Masterdata Management (MDM)

 |Beveiliging
 |Bescherming bieden tegen ongeautoriseerde toegang en datalekken
a|

 |Onderhoudbaarheid
 |Eenvoudig aanpasbaar en uitbreidbaar zijn
a|
|===

== Voorwaarden

De vijf profielen (zie <<_dataset>>) worden als _gesloten data_ aangeboden,
onder de _Grondslag Wettelijke Verplichting_.

== Architectuur

De waarde van de oplossing wordt beschreven over de as van twee _waardestromen_
[todo], waarbij de primaire rollen die van de landelijke en regionale
netbeheerder zijn. Elke stap in de waardestromen wordt uitgesplitst naar
_bedrijfsfuncties_, iets wat een netbeheerder "kan". Afsluitend worden de
bedrijfsfuncties uitgewerkt tot een bedrijfsprocesoverzicht. De
bedrijfsprocessen zijn wat een netbeheerder implementeert (_Build & Run_)
binnen de eigen organisatie om tot een duurzame ontsluiting van de
dataproducten te komen.

[NOTE]
====
Voor de architectuur van de oplossing wordt gebruik gemaakt van meerdere
perspectieven beschreven in het https://github.com/NBility-Model[NBility
model].
====

[NOTE]
====
De https://github.com/Netbeheer-Nederland/am-doelarchitectuur-datadelen[Doelarchitectuur
Datadelen] wordt als basis gebruikt voor de uitwerking van de oplossing.
====

=== Waardestromen

=== Bedrijfsfuncties

=== Bedrijfsprocessen

== Beslissingen en aannames

[cols="1, 1"]
|===
|Type |Beschrijving

|Beslissing
|Voor het beschrijven van de dataproducten wordt het CGMES gebruikt, aangevuld
 vanuit het CIM.

|Aanname
|_CGMES-interop_ is geen doel van de oplossing, door de uitbreiding nodig voor
 de regionale netbeheerder kan interoperabiliteit met CGMES niet gerealiseerd
 worden.

|Aanname
| Zowel landelijke als regionale netbeheerder is als gebruiker van de profielen
 beschikbaar om kwaliteit en toepasbaarheid te testen.
|===
