= Netcode Elektriciteit H13

Dit ontwerp beschrijft het beoogde gebruiksscenario voor het dataproducten
behorende bij de implementatie van
https://wetten.overheid.nl/BWBR0037940/2025-05-08#Hoofdstuk13[Netcode
Elektriciteit Hoofdstuk 13], alsmede de achterliggende architectuur en gemaakte
keuzes.

[NOTE]
====
include::partial$data_product.adoc[]
====

== Reikwijdte

Vanuit het kernteam Netdigitalisering is opdracht gegeven voor de start van de
eerste fase van de projectopdracht. Een eerste deel focust op het leggen van de
definities voor de samenwerking:

* standaardisering van de attribuutdefinities;
* opstellen informatiemodellen;
* identificatie van assets in elkaars net;
* onderzoeken beschikbaarheid data binnen de organisatie van de DSO en TSO
zoals beschreven in Netcode 13.

Het op te leveren product is een informatiemodel ten behoeve van de
uitwisseling van structurele _asset_ data tussen de netbeheerders. Deze dient
op zo'n manier vorm te zijn gegeven dat zij de basis vormt voor de tweede fase
waarin de uitwisseling verder wordt vormgegeven.

== Rollen

De dataproducten beschreven in dit ontwerp kennen meerdere stakeholders, elk
met een eigen verzameling behoeften en wensen. De <<_functionele_eisen>>
behorend bij elke rol worden in het volgende hoofdstuk beschreven.

#TODO: beheerder gesloten distributiesysteem?#

.Rollen
[cols="1, 2"]
|===
|Rol |Beschrijving

|Landelijke Netbeheerder (LNB)
|

|Regionale Netbeheerder (RNB)
|

|Toezichthouder
|
|===

== Functionele eisen

De dataproducten zijn onderheving aan functionele eisen: de informatievraag die
de dataproducten en onderliggende oplossing moeten beantwoorden. Daar waar van
toepassing zijn functionele eisen gerelateerd aan de
https://wetten.overheid.nl/BWBR0037940/2025-05-08#Hoofdstuk13[Netcode
Elektriciteit].

.Functionele eisen
[cols="1, 1, 3, 3, 2"]
|===
|ID |Als Rol |Wil ik |Want |NC13

|{counter:fr}
|LNB
|Inzicht in de structurele gegevens van elk afzonderlijk station van de RNB dat
 direct gekoppeld is aan het landelijk hoogspanningsnet
|
|§13.5.1, §13.5.2

|{counter:fr}
|LNB
|Inzicht in de structurele gegevens van elk achter een overdrachtspunt van een
 aansluiting gelegen deelnet van de RNB
|
|§13.5.3, §13.5.4

|{counter:fr}
|LNB
|Inzicht in de structurele gegevens van elk achter een overdrachtspunt van een
 aansluiting gelegen deelnet van elke beheerder van een _gesloten
 distributiesysteem_ aangesloten op het landelijk hoogspanningsnet
|
|§13.5.5

|===

== Dataset

De oplossing voor de implementatie van Netcode H13 bestaat uit het
implementeren van meerdere dataproducten voor o.a. connectiviteit,
netelementinformatie en de stabiele toestand van het elektriciteitsnet.

[NOTE]
====
Vanuit _Netbeheer Nederland_ is gekozen voor standaardisatie van de
data-uitwisseling op basis van het _Common Information Model_ (CIM). Het CIM is
een verzameling internationale standaarden die samen een informatiemodel vormen
voor het beschrijven van het elektriciteitsnet.

Als beginpunt van het beschrijven van de dataproducten is er gekozen voor de
_Common Grid Model Exchange Standard_ (CGMES). CGMES is een verzameling
*profielen* (dataproducten) die meerdere gebruiksscenario's beschrijven,
specifiek voor Transmission System Operators (TSO). De CGMES is daarmee een
specialisatie van het CIM, maar niet volledig toepasbaar voor het beschrijven
van het elektriciteitsnet van de regionale netbeheerder.

De in deze oplossing beschreven dataproducten worden om die reden aangevuld
vanuit het CIM, daar waar CGMES een functioneel gevraagd gebruiksscenario niet
ondersteunt.
====

Er zijn vijf verschillende profielen (dataproducten met bijbehorende datasets)
nodig om de informatievraag in te vullen:

.Profielen
[cols="1, 2"]
|===
|Profiel |Beschrijving

|Equipment (EQ)
|Eigenschappen van *netfuncties*, de connectiviteit van het
 elektriciteitsnet

|Operation (OP)
|Operationele meetwaarden, discreet en analoog. Meetwaarden zijn gemeten,
 berekend of geschat.

|Steady State Hypothesis (SSH)
|Stabiele toestand van het elektriciteitsnet

|Asset (AS)
|Fysieke eigenschappen van *netelementen*

|Market (MKT)
|Marktfacilitering binnen EU-markten
|===

=== Volume, variety, veracity, velocity

[NOTE]
====
include::partial$four_v.adoc[]
====

Voor alle vijf de profielen gelden dezelfde kenmerken:

[cols="1, 1"]
|===
|Type |Beschrijving

|Volume
|Laag, < 100MB (ongecomprimeerd)

|Variety
|Gestructureerd

|Veracity
|Medium, de gegevens zijn bij elke netbeheerder beschikbaar, maar niet elke
 netbeheerder heeft de volledige dataset tot haar beschikking.

|Velocity
|Laag, #TODO: hoe vaak worden de datasets uitgewisseld? Maandelijke, kwartaal,
 jaarlijks?#
|===

== Dataservice

=== Gebruiksscenario

Het volgende gebruiksscenario wordt ondersteund:

.Gebruiksscenario
[d2,svg,theme=4]
----
vars: {
  d2-config: {
    pad: 20
  }
}

shape: sequence_diagram

Landelijke\nNetbeheerder -> Landelijke\nNetbeheerder: "1. Verzamel gegevens"
Landelijke\nNetbeheerder -> Regionale\nNetbeheerder: "2. Lever Equipment Profile"

Regionale\nNetbeheerder -> Regionale\nNetbeheerder: "3. Verwerk koppelpunten"
Regionale\nNetbeheerder -> Landelijke\nNetbeheerder: "4. Lever Equipment Profile"
----

1.
2.
3.
4.

=== Kwaliteitseisen

Kwaliteitseisen (_non functionals_) beschrijven wat een oplossing moet *zijn*.
Voor dit ontwerp wordt de categorisering vanuit _ISO/IEC 25010_ aangehouden,
waar van toepassing.

.Kwaliteitseisen
[cols="1, 2, 2"]
|===
|Categorie |Beschrijving |Kwaliteitseisen

 |Prestaties
 |Snel en efficiënt functioneren, met minimale laadtijden en schaalbaar
a|

 |Overdraagbaarheid
 |Eenvoudig te verplaatsen of te migreren naar een andere omgeving
a|

 |Gebruiksvriendelijkheid
 |Intuïtief en makkelijk te gebruiken voor de eindgebruiker
a|

 |Betrouwbaarheid
 |Stabiel en foutbestendig, met een hoge beschikbaarheid
a|* integriteit -> Masterdata Management (MDM)

 |Beveiliging
 |Bescherming bieden tegen ongeautoriseerde toegang en datalekken
a|

 |Onderhoudbaarheid
 |Eenvoudig aanpasbaar en uitbreidbaar zijn
a|* Eén aanspreekpunt (team) per netbeheerder
|===

== Voorwaarden

De vijf profielen (zie <<_dataset>>) worden als _gesloten data_ aangeboden,
onder de _Grondslag Wettelijke Verplichting_.

== Architectuur

De oplossing wordt beschreven over de as van twee perspectieven: het produceren
van de profielen (_Build_) en het uitwisselen van de profielen (_Run_). Beide
perspectieven worden gestructureerd op basis van het bedrijfsprocesmodel van
_NBility_ en waar nodig aangevuld. De bedrijfsprocessen zijn wat een
netbeheerder implementeert binnen de eigen organisatie om tot een duurzame
ontsluiting van de dataproducten te komen.  Daarnaast vormen de te
implementeren processen de basis van de _features_ uit te voeren door de
netbeheerder.

De architectuur is opzettelijk abstract; *elke* netbeheerder wordt geacht een
eigen, passende invulling te geven aan de processen zoals beschreven in dit
ontwerp. Voorkeur ligt op het hergebruiken van bestaande faciliteiten binnen de
netbeheerder.

[NOTE]
====
Voor de architectuur van de oplossing wordt gebruik gemaakt van meerdere
perspectieven beschreven in het https://github.com/NBility-Model[NBility
model].
====

[NOTE]
====
De https://github.com/Netbeheer-Nederland/am-doelarchitectuur-datadelen[Doelarchitectuur
Datadelen] wordt als basis gebruikt voor de uitwerking van de oplossing.
Profielen (zie <<_dataset>>) zoals beschreven in dit ontwerp worden als
dataproduct beschreven en uitgewisseld.
====

=== Beschikbaar stellen van netbeheerdata (Build)

Elke netbeheerder is zowel producent als consument van de profielen. Daarmee
moet de netbeheerder in staat zijn om profielen te produceren onder de
_velocity_ die past bij het corresponderende profiel (zie
<<_volume_variety_veracity_velocity>>). Om dit te faciliteren implementeert de
netbeheerder onderstaande processen en diensten om de profielen gereed te maken
voor uitwisseling (zie <<_beschikbaar_stellen_van_netbeheerdata_run>>).

.Beschikbaar stellen van netbeheerdata (Build)
image::beschikbaar_stellen_van_netbeheerdata_build-20250602.svg[]

[cols="1, 2, 3"]
|===
|Type |Naam |Beschrijving

|Proces
|Vindbaar maken dataproduct
|Onder de _Doelarchitectuur Datadelen_ is elk profiel FAIR, waarbij dit proces
 het profiel vindbaar maakt. Vindbaar maken bestaat uit het registeren van het
 profiel bij de _Data Product Catalog_, samen met het publiceren van locatie van
 de dataset.

|Proces
|In behandeling nemen dataproductverzoek
|Bij implementatie of aanpassen van een profiel dient er aangesloten te worden
 op het voortbrengingsproces van de netbeheerder. Dit proces faciliteert
 prioritering van implementatie van het profiel.

|Proces
|Overeenkomen dataproduct
|Definitie, _refinement_ en uitvoering van de werkzaamheden om (aanpassingen
 in) het profiel te realiseren. Werkzaamheden vinden primair plaats in de
 _dataintegratieomgeving_ van de netbeheerder. Werkzaamheden uitvoerd in dit
 proces vinden hun uiting in de _Netbeheerderdataverstrekking_.

|Functie
|Master Data Management
|Opzetten, verbeteren en instandhouden van Master Data Management (MDM) binnen
 de netbeheerder. Dit omvat beleid, proces en procedure rondom het consistent
 en (waar nodig) persistent omgaan met identifiers.

|===

=== Beschikbaar stellen van netbeheerdata (Run)

Het uitwisselen van profielen bestaat uit het technisch ontsluiten van de
dataservices en datasets, toegangsbeheer, datakwaliteit, afhandelen van vragen
en het aannemen van -en communiceren over- functionele eisen.

.Beschikbaar stellen van netbeheerdata (Run)
image::beschikbaar_stellen_van_netbeheerdata_run-20250602.svg[]

[cols="1, 2, 3"]
|===
|Type |Naam |Beschrijving

|Proces
|Authenticatie en autorisatie
|Authenticeren en autoriseren van toegang tot profielen. Dit betreft de
 technische middelen om toegang te beveiligen, alsmede het beheren van de
 _identiteit_ van netbeheerders via een _Identity Access Management_-oplossing.

|Proces
|Leveren dataproduct
|Het (geautomatiseerd) beschikbaar stellen van de _dataset_ voor profielen, via
 de corresponderende _dataservice_.

|Functie
|Datakwaliteit borgen
|Het controleren en corrigeren van datakwaliteit van de profielen. Dit omhelst
 (geautomatiseerde) controle van de datasets tot beleid, proces en procedure
 voor correctie van datasets.

|Proces
|Behandelen vraag over dataproduct
|Vragen van afnemers van de profielen beantwoorden. Dit kan gaan om
 inhoudelijke vragen over gebruik van de profielen, maar ook
 datakwaliteitgerelateerde zaken. Interactie wordt vastgelegd als _Algemene
 klantzaak_ in de _Customer Management_-oplossing van de netbeheerder.

|Proces
|Vaststellen functionele eisen
|Sommige vragen leveren nieuwe functionele eisen op voor profielen. Dit proces
 handelt implementatievragen af vanuit _Netbeheer Nederland_ en faciliteert het
 consolideren van implementatievragen van andere netbeheerders, indien niet
 direct bij _Netbeheer Nederland_ belegd.

|===

== Beslissingen en aannames

[cols="1, 3"]
|===
|Type |Beschrijving

|Beslissing
|Voor het beschrijven van de dataproducten wordt het CGMES gebruikt, aangevuld
 vanuit het CIM.

|Aanname
|_CGMES-interop_ is geen doel van de oplossing, door de uitbreiding nodig voor
 de regionale netbeheerder kan interoperabiliteit met CGMES niet gerealiseerd
 worden.

|Aanname
|Minstens één landelijke en één regionale netbeheerder is als producent en
 consument van de profielen beschikbaar om kwaliteit en toepasbaarheid te
 testen.

|Aanname
|Netbeheerders factureren niet onderling voor het uitwisselen van de
 dataproducten.

|Aanname
|Elke netbeheerder implementeert de architectuur op basis van eigen middelen en
 invulling. Het ontkoppelpunt tussen netbeheerders zijn de profielen die
 uitgewisseld worden.

|Aanname
|Elke netbeheerder publiceert via de eigen
 dataintegratieomgeving/maatwerkproces decentraal de profielen. #TODO: is er
 een wens om te centraliseren, b.v. via TenneT of EDSN?#

|Aanname
|Netbeheerders maken gebruik van decentrale IAM-oplossingen, er wordt geen
 gefedereerde IAM-oplossing ingezet.

|Aanname
|De _NBNL Data Catalog_ is beschikbaar.

|Beslissing
|Er wordt afgeweken van de in _NBility_ beschreven waardestromen: _Overeenkomen
 dataproduct_ wordt gebruikt om dataproducten te realiseren. NBility definieert
 een complete waardestroom voor het realiseren van nieuwe producten, wat
 significant meerwerk in scope brengt voor dit ontwerp. Implementerende
 netbeheerders worden geadviseerd naar waardestroom _I.B Veranderen
 bedrijfsinrichting_ te kijken voor implementatie van een voortbrengingsproces.

|===
