= Nettopologie, belasting en capaciteit (NBC)

Dit ontwerp beschrijft het beoogde gebruiksscenario voor het dataproduct
_NBC_, alsmede de achterliggende architectuur en gemaakte keuzes.

[NOTE]
====
include::partial$data_product.adoc[]
====

== Reikwijdte

Het doel is om marktpartijen voldoende informatie over het net te geven waarmee ze in staat zijn om gerichte individuele of collectieve voorstellen voor gv-klanten te doen, waardoor het net beter wordt benut.

.Rollen
[cols="1, 2"]
|===
|Rol |Beschrijving

|Netbeheerder
|Vennootschap die op grond van de wet is aangewezen voor het beheer van een of  meer energienetten, niet zijnde gesloten distributiesystemen

|GV-klant
|Afnemer met een aansluiting met een totale maximale capaciteit groter dan 3x80  Ampère voor elektriciteit of 40 m3(n) per uur voor gas, of een aansluiting op een gesloten distributiesysteem, of een aansluiting van een afnemer zoals  bedoeld in artikel 1, tweede of derde lid, van de Elektriciteitswet 1998

|Technisch adviseur
|Een organisatie of persoon die faciliteert bij het opzetten van een  Energiehub.

|Marktpartij
|Derden die vanuit overige use cases belang hebben bij de informatie verstrekt  vanuit dit dataproduct.

|===


== Functionele eisen

De dataproducten zijn onderheving aan functionele eisen: de informatievraag die
de dataproducten en onderliggende oplossing moeten beantwoorden.

.Functionele eisen
[cols="1, 1, 3, 3"]
|===
|ID |Als Rol |Wil ik |Want

|{counter:fr}
|Als energie(hub)adviseur 
|Inzicht in de operationele limiet en belasting in de voor mij relevante netfuncties (assets) over de dag heen gedurende het jaar, zowel van de huidige als de toekomstige situatie
|Ik wil op basis hiervan een gedetailleerd beeld krijgen van de vrije ruimte en schaarste (_speelruimte_)

|{counter:fr}
|Als energie(hub)adviseur 
|Inzicht in de operationele limiet en belasting in de voor mij relevante netfuncties (assets) over de dag heen gedurende het jaar, zowel van de huidige als de toekomstige situatie
|Individuele en collectieve oplossingen verkennen en adequate voorstellen doen richting netbeheerder

|{counter:fr}
|Als energie(hub)adviseur 
|Inzicht in de operationele limiet en belasting in de voor mij relevante netfuncties (assets) over de dag heen gedurende het jaar, zowel van de huidige als de toekomstige situatie
|Bijdragen aan beter benutten van het net en hiermee GV-klanten helpen die geen (extra) capaciteit kunnen krijgen

|{counter:fr}
|Energie(hub)adviseur 
|Inzicht de nettopologie van het gebied waar ik me op richt, samen met het hoger liggende gebied
|Zo kan ik potentiële kandidaten voor een ehub identificeren (netburen)

|{counter:fr}
|Energie(hub)adviseur 
|Inzicht de nettopologie van het gebied waar ik me op richt, samen met het hoger liggende gebied
|Ik kan dan bepalen hoe de aansluitingen, verbindingen en stations onderling invloed op elkaar uitoefenen én hier de juiste specificaties aan kan koppelen om mee door te rekenen

|{counter:fr}
|Energie(hub)adviseur
|Inzicht de nettopologie van het gebied waar ik me op richt, samen met het hoger liggende gebied
|Ik krijg dan handelingsperspectief om met slimme oplossingen te komen om het net beter te benutten

|{counter:fr}
|Netbeheerder
|Enkel inzicht verstrekken vanuit *use case*-perspectief.
|Ik moet voldoen aan beleid rondom het communiceren van nettopologie van de netbeheerder.

|{counter:fr}
|Technisch adviseur
|Inzicht in de (technische) zekeringswaarde van het overdrachtspunt.
|Ik wil inzicht in de bandbreedte van energieverbruik.

|{counter:fr}
|Technisch adviseur
|Inzicht in de kabels en of deze onder congestie (afname & invoeding) liggen.
|Ik moet aansluitingen op deze kabels uitsluiten van deelname aan een Energiehub

|{counter:fr}
|Technisch adviseur
|Inzicht in de individuele capaciteit van kabels.
|Ik wil onderlinge energie-uitwisseling tussen deelnemers aan een Energiehub toetsen/doorrekenen.

|{counter:fr}
|Marktpartij
|Inzicht in de capaciteit en restcapaciteit (vrije ruimte) op veldniveau en secundaire zijde(s) van de relevante transformatoren, als _operationele limiet_.
|Dit geeft inzicht in de capaciteit

|{counter:fr}
|Marktpartij
|Inzicht in de belasting op veldniveau en secundaire zijde(s) van de relevante  transformatoren; 2 jaar historische kwartierwaardes (gemeten) voor invoeding &  afname (gesplitst).
|#TODO: ?#

|{counter:fr}
|Technisch adviseur
|Inzicht in de wachtrij (gevraagd vermogen) ?
|Ik wil de wachtrij vrijmaken door deelnemers aangesloten op een knelpunt  (kabel) onderdeel te maken van een Energiehub.

|===

== Dataservice

=== Gebruiksscenario

Het volgende gebruiksscenario wordt ondersteund:

.Gebruiksscenario
[d2,svg,theme=4]
----
shape: sequence_diagram

vars: {
  d2-config: {
    pad: 20
  }
}

"TA": "Technisch\nAdviseur"
"GV-klant": "GV\nklant"
"NB": "Netbe-\nheerder"

"TA" -> "GV-klant": "1. Verzoekt om NBC tbv advies"
"GV-klant" -> "NB": "2. Verzoekt om NBC"
"NB" -> "GV-klant": "3. Verzoekt om authenticatie + welke EAN"
"GV-klant" -> "NB": "4. Authenticeert en levert EAN"
"NB" -> "NB": "5. Bepaalt NBC op basis van EAN voor afgaand veld + station"
"NB" -> "GV-klant": "6. Levert NBC-gegevens"
"GV-klant" -> "TA": "7. Levert NBC-gegevens"
"TA" -> "TA": "8. Maakt advies"
"TA" -> "GV-klant": "9. Geef advies"

----

1. Verzoekt om NBC tbv advies: Technisch adviseur verzoekt de GV-klant om NBC-gegevens die hij nodig heeft voor zijn advies;
2. Verzoekt om NBC: De GV-klant vraagt zijn netbeheerder om NBC-gegevens;
3. Verzoekt om authenticatie + welke EAN: De netbeheerder authenticeert de GV-klant en verzoekt om de betreffende EAN;
4. Authenticeert en levert EAN: De GV-klant authenticeert zich bij de netbeheerder en levert de betreffende EAN;
5. Bepaalt NBC op basis van EAN voor afgaand veld + station: De netbeheerder bepaalt het afgaande veld en bijbehorende station horende bij dit EAN en vervolgens de NBC-gegevens;
6. Levert NBC-gegevens: De netbeheerder levert de gevraagde NBC-gegevens aan de GV-klant;
7. Levert NBC-gegevens: De GV-klant levert de NBC-gegevens aan de Technische Adviseur; 
8. Maakt advies: De Technische Adviseur gebruikt de NBC-gegevens om een advies te maken voor de EAN van de GV-klant;
9. Geef advies: De Technische Adviseur geeft zijn advies aan de GV-klant.

=== Architectuur

Vanuit architectuurperspectief zijn de volgende keuzes gemaakt:

.Architectuur
[d2,svg,theme=4,scaledwidth=100%]
----
vars: {
  d2-config: {
    pad: 20
  }
}

grid-rows: 5
grid-columns: 4

vertical-gap: 80
horizontal-gap: 160

Netbeheerder.class: [noun; business]
Consumer.class: [noun; business]
4.class: empty
5.class: empty

6.class: empty
Extract.class: [verb; business]
Transform.class: [verb; business]
Load.class: [verb; business]

"MijnOmgeving/Maatwerk".class: [noun; application]
"Data Product".class: [noun; application]
"NBNL Dataportaal".class: [noun; application]
7.class: empty

8.class: empty
"JSON File".class: [artifact; technology]

Extract -> Transform: "triggers"
Transform -> Load: "triggers"
"Data Product" -> "Extract": "serves"
"NBNL Dataportaal" -> "Data Product": "accesses (read)"
Extract -> Consumer: "serves"
"JSON File" -> "Data Product": "realises"
"MijnOmgeving/Maatwerk" -> "Data Product": "accesses (read)"
"Netbeheerder" -> "MijnOmgeving/Maatwerk": "assigned to"

legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  business_color: "" {
    style: {
      fill: "#ffffaf"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  business_text: "Business" {
    shape: text
  }
  application_color: "" {
    style: {
      fill: "#afffff"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  application_text: "Application" {
    shape: text
  }
  technology_color: "" {
    style: {
      fill: "#afffaf"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  technology_text: "Technology" {
    shape: text
  }
}

classes: {
  *: {
    style: {
      shadow: true
    }
  }
  empty: {
    label: ""
    style: {
      fill: transparent
      stroke-width: 0
    }
  }
  verb: {
    style: {border-radius: 30}
  }
  noun: {
    style: {border-radius: 4}
  }
  artifact: {shape: page}
  business: {
    style: {
      fill: "#ffffaf"
    }
  }
  application: {
    style: {
      fill: "#afffff"
    }
  }
  technology: {
    style: {
      fill: "#afffaf"
    }
  }
}

----

* de structuur
  (https://netbeheer-nederland.github.io/docs-dev/dp-netburen/latest/index.html[informatiemodel])
  van de dataset is gebaseerd op het _Begrippenmodel NBNL_ en het _Common
  Information Model_;
* aanlevering van de dataset vanuit de netbeheerder geschiedt via JSON-bestand.
* het dataproduct is vindbaar via het NBNL Dataportaal.

== Dataset

De dataset beschrijft de potentiële deelnemers aan een _Energiehub_, inclusief
relevante nettopologie en capaciteit & belasting.

=== Volume, variety, veracity, velocity

[NOTE]
====
include::partial$four_v.adoc[]
====

[cols="1, 1"]
|===
|Type |Beschrijving

|Volume
|Laag, < 100MB (ongecomprimeerd)

|Variety
|Gestructureerd

|Veracity
|Midden, de dataset wordt op basis van verschillende interne bronnen van de
 netbeheerder samengesteld

|Velocity
|Laag, datasets worden op verzoek samengesteld

|===

== Voorwaarden
De lijst van grondslagen is te vinden op: https://www.autoriteitpersoonsgegevens.nl/themas/basis-avg/avg-algemeen/grondslagen-avg-uitgelegd.

De grondslagen zijn:

- Toestemming

- Overeenkomst

- Wettelijke verplichting

- Vitaal belang

- Taak van algemeen belang of

- uitoefening van openbaar gezag

- Gerechtvaardigd belang


Dit dataproduct wordt als _gesloten data_ aangeboden, onder de _Grondslag
Toestemming_. Voor een GV-klant is toestemming impliciet verleend voor eigen
aansluiting(en) vanuit de authenticatie en autorisatie van de GV-klant door de
netbeheerder.

== Beslissingen en aannames

[cols="1, 1"]
|===
|Type |Beschrijving

|Aanname
|Nettopologie, belasting en capaciteit in één dataproduct

|Aanname
|Nettopologie is open data (GEMS)

|Aanname
|GEMS beslist dat assetbelastingsdata van het afgaande veld gedeeld mag worden. Zelfs wanneer hierdoor de belasting van individuele GV- of KV-aansluitingen afleidbaar wordt.

|Aanname
|GEMS heeft geen problemen met het delen van capaciteit (operationele limiet)

|Beslissing
|Uitlevering van de MVP huidige belasting, capaciteit en nettopologie zal in Q4 nog via de decentrale processen plaatsvinden. Het is namelijk niet haalbaar voor EDSN om voor kerst 2025 een proces te realiseren via het centraal dataportaal o.b.v. toestemming. 

|Aanname
|De processen voor de uitlevering van netburen is reeds ingericht; we kunnen voor deze dataproducten (nettopologie, belasting en capaciteit) hier efficiënt gebruik van maken.

|DeepDive
|kVA? Of alleen werkelijk vermogen?

|DeepDive
|Bedrijfszeker installatie vermogen (BZIV) of ook additionele niet redundante vermogen (ANRV)?

|DeepDive
|N-1?

|DeepDive
|Tot welk detailniveau? Route / kabel tussen aangeslotenen, etc.?

|DeepDive
|Levering/teruglevering?

|Deepdive
|Als we capaciteit in kVa doen; hoe gaan we dan om met verschil in eenheid?

|Aanname
|Nettopologie, belasting en capaciteit in één dataproduct

|Aanname
|Geen gegevens over kabels

|Aaname
|Geolocatie alleen over stations

|Hieronder
|Netburen

|Aanname
|De oplossing heeft als reikwijdte *enkel* het ondersteunen van de verkennende
 fase van een Energiehub.

|Aanname
|Lokale overheden zijn geen stakeholders binnen deze oplossing.

|Aanname
|Het proces behorende bij _optimaliseren achter de meter_ ligt in het domein
 van de Technisch adviseur en is daarmee out-of-scope voor het ontwerp.

|Aanname
|Het combineren van datasets levert mogelijk meer informatie ...

|Beslissing
|Kabelinformatie is out-of-scope voor het ontwerp.

|Aanname
|Voor nettopologie wordt uitgegaan van de normaalstand van het net.

|Aanname
|Meetgegevens voor veld en transformator zijn enkel geldig binnen de
 normaalstand. Indien de normaalstand gewijzigd is binnen de historische periode
 zijn de meetwaardes gedaan voor de wijziging niet geldig en worden *niet*
 gecommuniceerd.

|Aanname
|Er worden geen geocoördinaten in het informatiemodel opgenomen.

|Aanname
|Er wordt geen informatie gecommuniceerd over netbeveiliging, _n-1_ wordt
geabstraheerd als onderdeel van de nettopologie.

|Aanname
|Er wordt geen informatie gecommuniceerd over wachtrijen en kortsluitstromen.

|Aanname
|Belasting wordt voor de afgelopen twee jaar in kwartierwaardes gecommuniceerd,
 capaciteit wordt op basis van een enkele operationele limiet gecommuniceerd.

|Beslissing
|De technisch adviseur heeft geen behoefte aan inzicht in capaciteit en
 belasting binnen de nettopologie.

|Beslissing
|De technisch adviseur heeft heeft behoefte aan de kWmax piek voor elke
 aansluiting, maar berekent deze zelf op basis van de verbruiksgegevens.

|===
