= Design

Dit ontwerp beschrijft het beoogde gebruiksscenario voor het dataproduct
_Netbewust Laden_, alsmede de achterliggende architectuur en gemaakte keuzes.

== Reikwijdte

[todo]

== Dataservice

=== Gebruiksscenario

Het volgende gebruiksscenario wordt ondersteund:

.Gebruiksscenario
[d2,svg,theme=4]
----
shape: sequence_diagram

vars: {
  d2-config: {
    pad: 20
  }
}
----

1. ...

=== Architectuur

Vanuit architectuurperspectief zijn de volgende keuzes gemaakt:

.Architectuur
[d2,svg,theme=4,scaledwidth=100%]
----
vars: {
  d2-config: {
    pad: 20
  }
}
----

* de structuur (logisch model) van de dataset behorende bij het dataproduct is
  gebaseerd op het conceptuele model _Begrippenmodel NBNL_ en het _Common
  Information Model_;
* aanlevering van de dataset vanuit de netbeheerder geschiedt via JSON-bestand.
  Een JSON Schema op basis van het logisch model is hiervoor beschikbaar
  gemaakt;
* netbeheerders leveren de dataset aan via een eigen bestandslocatie;
* het dataproduct [todo] is vindbaar via het EDSN Dataportaal.

== Dataset

De dataset beschrijft ...

.Architectuur
[d2,svg,theme=4,scaledwidth=100%]
----
vars: {
  d2-config: {
    pad: 20
  }
}

grid-rows: 5
grid-columns: 4

vertical-gap: 200
horizontal-gap: 200

1.class: empty
"Asset Management".class: enterprise
"Grid Measurement".class: grid
2.class: empty

Start.class: dataset
"Net Model Management".class: grid
"Topology Processing".class: grid
"State Estimation".class: grid

3.class: empty
GIS.class: enterprise
4.class: empty
"Market Facilitation".class: market

Start -> "Net Model Management"
"Net Model Management" -> "Topology Processing": "Equipment Profile\nSSH Profile"
"Net Model Management" -> GIS: "Equipment Profile"
"Net Model Management" -> "Grid Measurement": "Equipment Profile"
"Topology Processing" -> "State Estimation": "Topology Profile"
"Grid Measurement" -> "Topology Processing": "Operations Profile"
"Grid Measurement" -> "State Estimation": "Operations Profile"
GIS -> "Market Facilitation": "Geographical Location\nProfile"
"Asset Management" -> "Net Model Management": "Asset Profile"
"Topology Processing" -> "Market Facilitation": "Topology Profile"
"State Estimation" -> "Market Facilitation": "State Variables Profile"

legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  iec61968_color: "" {
    style: {
      fill: "#d1e7c2"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61968_text: "IEC61968 (Enterprise)" {
    shape: text
  }
  iec61970_color: "" {
    style: {
      fill: "#eccfcb"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61970_text: "IEC61970 (Grid)" {
    shape: text
  }
  iec62325_color: "" {
    style: {
      fill: "#fffbef"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec62325_text: "IEC62325 (Market)" {
    shape: text
  }
}

classes: {
  empty: {
    label: ""
    style: {
      fill: transparent
      stroke: transparent
    }
  }
  grid: {
    style: {
      fill: "#eccfcb"
      shadow: true
    }
  }
  enterprise: {
    style: {
      fill: "#d1e7c2"
      shadow: true
    }
  }
  market: {
    style: {
      fill: "#fffbef"
      shadow: true
    }
  }
  dataset: {
    style: {
      shadow: true
    }
    width: 80
    height: 80
    shape: circle
  }
}
----

=== Volume, variety, veracity, velocity

[NOTE]
====
include::partial$four_v.adoc[]
====

[cols="1, 1"]
|===
|Type |Beschrijving

|Volume
|Midden, < 1000MB (ongecomprimeerd)

|Variety
|Gestructureerd

|Veracity
|Medium, sluit aan op het bestaande inzicht van de netbeheerder in het LS-net

|Velocity
|Laag, dataset verandert wanneer [todo]
|===

== Voorwaarden

Dit dataproduct wordt als _open data_ aangeboden.

== Beslissingen en aannames

[cols="1, 1"]
|===
|Type |Beschrijving

|Beslissing
|Dataproduct [todo] wordt als decentraal dataproduct onder een gecentraliseerd schema beschikbaar gemaakt.
|===
