= Rijksinpsectie Data Infrastructuur (RDI) Data delen

Dit ontwerp beschrijft het beoogde gebruiksscenario voor het dataproduct
_RDI_, alsmede de achterliggende architectuur en gemaakte keuzes.

[NOTE]
====
include::partial$data_product.adoc[]
====

== Reikwijdte

Per 1-1-2027 wordt de salderingsregeling afgeschaft. Klanten die op dat moment nog een ouderwetse terugdraaimeter hebben kunnen dan nog altijd salderen en dat brengt rechtsongelijkheid. Om die reden worden de ouderwetse terugdraaimeters verboden en moet overal een meter hangen met een aparte registratie voor levering en teruglevering. 

De netbeheerders zullen om die reden opnieuw de slimme meter gaan aanbieden bij de aangeslotenen. Wordt de slimme meter geweigerd of lukt het niet om een andere meter te plaatsen dan ontstaat de verplichting dit te melden bij de RDI obv de gegevens zoals hiernaast vermeld.

Er lopen nog gesprekken met verschillende partijen over welke informatie exact moet worden aangeleverd en via welke weg, waarbij op dit moment de GUE als belangrijkste kandidaat wordt gezien door onder andere de RDI zelf. *De informatie uitwisseling zal starten per 1-1-2026.*

== Functionele eisen

Het dataproduct is onderheving aan functionele eisen: wat het dataproduct moet *doen*.

.Functionele eisen
[cols="1, 1, 1"]
|===
|Als Rol |Wil ik |Want

|Energieleverancier (EL)
|Een uniform overzicht met aansluitingen en contactgegevens van al mijn klanten (klantgegevens)
|Deze informatie moet ik naar het Aangeslotene Register sturen

|Netbeheerder (RNB)
|Een uniform overzicht met aansluitingengegevens van mijn aangeslotenen
|Deze informatie moet ik naar het Aangeslotene Register sturen

|Netbeheerder
|Een uniform overzicht met klantinteractiegegevens van mijn aangeslotenen met een 'ouderwetse terugdraaimeter'
|Deze informatie moet ik naar de Rijksinspectie Digitale Infrastructuur sturen

|Netbeheerder
|Een uniform overzicht met meterinformatie van mijn aangeslotenen met een 'ouderwetse terugdraaimeter'
|Deze informatie moet ik naar de Rijksinspectie Digitale Infrastructuur sturen

|Aangeslotene Register (AR)
|Een uniform overzicht met aansluitingen en contactgegevens van al mijn klanten met een 'ouderwetse terugdraaimeter' (aangeslotenegegevens)
|Deze informatie moet ik naar de Rijksinspectie Digitale Infrastructuur sturen

|Rijksinspectie Digitale Infrastructuur (RDI)
|Een uniform overzicht met aansluitingen en contactgegevens van alle aangeslotenen met een 'ouderwetse terugdraaimeter'
|Ik wens de netbeheerder te instrueren van deze aangesloten de meter te vervangen 

|===

== Dataservice

=== Gebruiksscenario

Het volgende gebruiksscenario wordt ondersteund:

.Gebruiksscenario
[d2,svg,theme=4]
----
shape: sequence_diagram

vars: {
  d2-config: {
    pad: 20
  }
}

EL
RNB
AR
RDI

EL -> AR: 1. Lever dataset\: klantgegevens
RNB -> AR: 2. Lever dataset\: aansluitingengegevens
AR -> RDI: 3. Lever dataset\: aangeslotenegegevens
RNB -> RDI: 4. Lever dataset\: klantinteractiegegevens
RNB -> RDI: 5. Lever dataset\: meterinformatie
RDI -> RNB: 6. Meterwisselopdracht
----

1. _Toelichting gebeurtenis_

=== Architectuur

Vanuit architectuurperspectief zijn de volgende keuzes gemaakt:

.Architectuur
[d2,svg,theme=4,scaledwidth=100%]
----

vars: {
  d2-config: {
    pad: 20
  }
}

grid-rows: 1
grid-columns: 2

vertical-gap: 80
horizontal-gap: 160

"Blokje".class: [noun; business]
2_1.class: invisible

legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  business_color: "" {
    style: {
      fill: "#ffffaf"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  business_text: "Business" {
    shape: text
  }
  application_color: "" {
    style: {
      fill: "#afffff"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  application_text: "Application" {
    shape: text
  }
  technology_color: "" {
    style: {
      fill: "#afffaf"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  technology_text: "Technology" {
    shape: text
  }
}

classes: {
  *: {
    style: {
      shadow: true
    }
  }
  empty: {
    label: ""
    style: {
      fill: transparent
      stroke-width: 0
    }
  }
  verb: {
    style: {border-radius: 30}
  }
  noun: {
    style: {border-radius: 4}
  }
  artifact: {shape: page}
  business: {
    style: {
      fill: "#ffffaf"
    }
  }
  application: {
    style: {
      fill: "#afffff"
    }
  }
  technology: {
    style: {
      fill: "#afffaf"
    }
  }
  invisible: {
    style.opacity: 0
    label: ""
  }
}

----

* _Toelichting_.

== Dataset

_De dataset bevat..._

=== Volume, variety, veracity, velocity

[NOTE]
====
include::partial$four_v.adoc[]
====

[cols="1, 1"]
|===
|Type |Beschrijving

|Volume
|_Laag, Midden, Hoog. Met toelichting._

|Variety
|_Gestructureerd, Ongestructureerd. Met toelichting._

|Veracity
|_Laag, Midden, Hoog. Met toelichting._

|Velocity
|Midden, minimaal één maal per 24 uur (zie functionele eisen)
|===

== Voorwaarden

Dit dataproduct wordt als _open/gesloten data_ aangeboden.

== Beslissingen en aannames

[cols="1, 1"]
|===
|Type |Beschrijving

|Aanname
|_Aanname_

|Beslissing
|_Beslissing_


|===
