= Rijksinspectie Data Infrastructuur (RDI)

Dit ontwerp beschrijft het beoogde gebruiksscenario voor het dataproduct
_RDI_, alsmede de achterliggende architectuur en gemaakte keuzes.

[NOTE]
====
include::partial$data_product.adoc[]
====

== Reikwijdte

Per 1-1-2027 wordt de salderingsregeling afgeschaft. Klanten die op dat moment nog een ouderwetse terugdraaimeter hebben kunnen dan nog altijd salderen en dat brengt rechtsongelijkheid. Om die reden worden de ouderwetse terugdraaimeters verboden en moet overal een meter hangen met een aparte registratie voor levering en teruglevering. 

De netbeheerders zullen om die reden opnieuw de slimme meter gaan aanbieden bij de aangeslotenen. Wordt de slimme meter geweigerd of lukt het niet om een andere meter te plaatsen dan ontstaat de verplichting dit te melden bij de Rijksinspectie Digitale Infrastructuur (RDI) op basis van informatie over de meter, de aangeslotene en de klantinteractie.

Er lopen nog gesprekken met verschillende partijen over welke informatie exact moet worden aangeleverd en via welke weg, waarbij op dit moment de Gegevensuitwisselingsentiteit (GUE) als belangrijkste kandidaat wordt gezien door onder andere de RDI zelf. *De informatie uitwisseling zal starten per 1-1-2026.*

== Functionele eisen

Het dataproduct is onderheving aan functionele eisen: wat het dataproduct moet *doen*.

.Functionele eisen
[cols="1, 1, 1"]
|===
|Als Rol |Wil ik |Want

|RDI
|Een uniform overzicht van 'ouderwetse terugdraaimeters' (metergegevens)
|Deze meters moeten vervangen worden 

|RDI
|Een uniform overzicht van de klanten die deze meters gebruiken (aansluitingsgegevens)
|Deze aangeslotenen moeten hun meter laten vervangen

|RDI
|Een uniform overzicht met contactgegevens van deze aangeslotenen (klantcontactgegevens)
|Deze aangeslotenen moeten aangeschreven worden

|RDI
|Een uniform overzicht van de interactie (communicatie) met deze aangeslotenen (klantinteractiegegevens)
|Ik wil weten wat de status van de meterwissel is

|RDI
|Een uniform overzicht van de eigenschappen van de meter (metergegevens)
|Ik wil een geschikte vervangende meter aanbieden

|===

== Dataservice

Er moet gekozen worden tussen een tweetal scenario's: centraal en decentraal. 

* In het centrale scenario verzamelt en integreert EDSN alle datasets en biedt het aan als één dataset (meterwisselgegevens);
* In het decentrale scenario biedt elke regionale netbeheerder haar eigen dataset aan en zullen deze datasets nog verrijkt moeten worden met klantgegevens.

=== Gebruiksscenario: centraal dataproduct

.Gebruiksscenario
[d2,svg,theme=4]
----
shape: sequence_diagram

vars: {
  d2-config: {
    pad: 20
  }
}

Rijksinspectie\nDigitale Infrastructuur
"EDSN\n "
Regionale\nnetbeheerder
Aangeslotene\nRegister

Rijksinspectie\nDigitale Infrastructuur -> "EDSN\n ": 1. Verzoek meterwisselgegevens

"EDSN\n " -> Regionale\nnetbeheerder: 2. Verzoek metergegevens
Regionale\nnetbeheerder -> "EDSN\n ": 3. Lever metergegevens
"EDSN\n " -> Aangeslotene\nRegister: 4. Verzoek aangeslotenegegevens
Aangeslotene\nRegister -> "EDSN\n ": 5. Lever aangeslotenegegevens
"EDSN\n " -> Regionale\nnetbeheerder: 6. Verzoek klantinteractiegegevens
Regionale\nnetbeheerder -> "EDSN\n ": 7. Lever klantinteractiegegevens

"EDSN\n " -> "EDSN\n ": 8. Integreer gegevens

"EDSN\n " -> Rijksinspectie\nDigitale Infrastructuur: 9. Lever meterwisselgegevens

----

1. De RDI verzoekt om meterwisselgegevens 
2. EDSN verzoekt om metergegevens van ouderwetse terugdraaimeter
3. De RNB levert metergegevens
4. EDSN verzoekt om aangeslotenengegevens (aansluitingsgegevens en klantcontactgegevens) behorende bij deze meters
5. Het Aangeslotene Register levert aangeslotenegegevens (aansluitingsgegevens en klancontactgegevens)
6. EDSN verzoekt om klantinteractiegegevens van deze klanten
7. De RNB levert klantinteractiegegevens
8. EDSN combineert de metergegevens, klantinteratiegegevens en de aangeslotnegegevens tot meterwisselgegevens
9. EDSN levert meterwisselgegevens


=== Gebruiksscenario: decentraal dataproduct

.Gebruiksscenario
[d2,svg,theme=4]
----
shape: sequence_diagram

vars: {
  d2-config: {
    pad: 20
  }
}

Rijksinspectie\nDigitale Infrastructuur
Regionale\nnetbeheerder
Aangeslotene\nRegister

Rijksinspectie\nDigitale Infrastructuur -> Regionale\nnetbeheerder: 1. Verzoek metergegevens
Regionale\nnetbeheerder -> Rijksinspectie\nDigitale Infrastructuur: 2. Lever metergegevens
Rijksinspectie\nDigitale Infrastructuur -> Aangeslotene\nRegister: 3. Verzoek aangeslotenegegevens
Aangeslotene\nRegister -> Rijksinspectie\nDigitale Infrastructuur: 4. Lever aangeslotenegegevens
Rijksinspectie\nDigitale Infrastructuur -> Regionale\nnetbeheerder: 5. Verzoek klantinteractiegegevens
Regionale\nnetbeheerder -> Rijksinspectie\nDigitale Infrastructuur: 6. Lever klantinteractiegegevens

Rijksinspectie\nDigitale Infrastructuur -> Rijksinspectie\nDigitale Infrastructuur: 7. Integreer gegevens

----

1. De RDI verzoekt om metergegevens van ouderwetse terugdraaimeter
2. De RNB levert metergegevens
3. De RDI verzoekt om aangeslotenengegevens (aansluitingsgegevens en klantcontactgegevens) behorende bij deze meters
4. Het Aangeslotene Register levert aangeslotenegegevens (aansluitingsgegevens en klancontactgegevens)
5. De RDI verzoekt om klantinteractiegegevens van deze klanten
6. De RNB levert klantinteractiegegevens
7. De RDI combineert de metergegevens, klantinteratiegegevens en de aangeslotnegegevens tot meterwisselgegevens

=== Architectuur

Vanuit architectuurperspectief zijn de volgende keuzes gemaakt:

.Architectuur
[d2,svg,theme=4, width=100%]
----
vars: {
  d2-config: {
    pad: 20
  }
}

grid-rows: 5
grid-columns: 4

vertical-gap: 80
horizontal-gap: 160

1.class: empty
EDSN.class: [noun; business]
2.class: empty
3.class: empty

Netbeheerder.class: [noun; business]
Broker.class: [noun; business]
Consumer.class: [noun; business]
4.class: empty

5.class: empty
Extract.class: [verb; business]
Transform.class: [verb; business]
Load.class: [verb; business]

"MijnOmgeving/Maatwerk".class: [noun; application]
"Data Product".class: [noun; application]
"NBNL Dataportaal".class: [noun; application]
6.class: empty

7.class: empty
"JSON File".class: [artifact; technology]

Extract -> Transform: "triggers"
Transform -> Load: "triggers"
"Data Product" -> "Extract": "serves"
"NBNL Dataportaal" -> "Data Product": "accesses (read)"
Extract -> Consumer: "serves"
EDSN -> Broker: "assigned to"
Broker -> Extract: "assigned to"
"JSON File" -> "Data Product": "realises"
"MijnOmgeving/Maatwerk" -> "Data Product": "accesses (read)"
"Netbeheerder" -> "MijnOmgeving/Maatwerk": "assigned to"

legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  business_color: "" {
    style: {
      fill: "#ffffaf"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  business_text: "Business" {
    shape: text
  }
  application_color: "" {
    style: {
      fill: "#afffff"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  application_text: "Application" {
    shape: text
  }
  technology_color: "" {
    style: {
      fill: "#afffaf"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  technology_text: "Technology" {
    shape: text
  }
}

classes: {
  *: {
    style: {
      shadow: true
    }
  }
  empty: {
    label: ""
    style: {
      fill: transparent
      stroke-width: 0
    }
  }
  verb: {
    style: {border-radius: 30}
  }
  noun: {
    style: {border-radius: 4}
  }
  artifact: {shape: page}
  business: {
    style: {
      fill: "#ffffaf"
    }
  }
  application: {
    style: {
      fill: "#afffff"
    }
  }
  technology: {
    style: {
      fill: "#afffaf"
    }
  }
}

----


1. De structuur van de dataset is gebaseerd op het _Begrippenmodel NBNL_ en het _Common Information Model_;
2. Aanlevering van de metergegevens, de aangeslotenegegevens en de klantinteractiegegevens geschiedt via JSON-bestanden

== Dataset

=== Volume, variety, veracity, velocity

[NOTE]
====
include::partial$four_v.adoc[]
====

In centrale dataproduct scenario is er één dataset: de meterwisselgegevens. In het decentrale scenario zijn er drie datasets: metergegevens, aangeslotenegegevens en klantinteractiegegevens. Deze worden echter geïntegreerd tot één dataset.

[cols="1, 3"]
|===
|Type |Beschrijving

|Volume
|Laag, na de initiële verlading volgen alleen maar incrementele verladingen

|Variety
|Gestructureerd

|Veracity
|Hoog

|Velocity
|Laag, na de initiële verlading volgen alleen maar incrementele verladingen
|===

== Voorwaarden

Dit dataproduct wordt als _gesloten data_ aangeboden, onder de _Grondslag Toestemming_.


== Beslissingen en aannames

[cols="1, 1"]
|===
|Type |Beschrijving

|Aanname
|Er is doel/binding voor alle datasets

|Aanname
|Het Aangeslotene Register kan de aangeslotenegegevens leveren (afhankelijkheid met de energieleverancier voor de klantcontactgegevens en de kopelbaarheid met de aansluitingsgegevens van de RNB)

|Aanname
|Aangeslotenegegevens, klantinteractiegegevens en meteregevens kunnen gekoppeld worden

|Aanname
|De dataverlading incrementeel

|Aanname
|De aansluitingengegevens die de RNB's aanleveren bevatten alleen gegevens van aansluitingen met een  'ouderwetse terugdraaimeter'. Dus niet _verzenden en dan filteren_, maar _filteren en dan verzenden_. Idem voor klantinteractiegegevens en meteringegevens

|===
