= Rijksinspectie Data Infrastructuur (RDI)

Dit ontwerp beschrijft het beoogde gebruiksscenario voor het dataproduct
_RDI_, alsmede de achterliggende architectuur en gemaakte keuzes.

[NOTE]
====
include::partial$data_product.adoc[]
====

== Reikwijdte

Per 1-1-2027 wordt de salderingsregeling afgeschaft. Klanten die op dat moment nog een ouderwetse terugdraaimeter hebben kunnen dan nog altijd salderen en dat brengt rechtsongelijkheid. Om die reden worden de ouderwetse terugdraaimeters verboden en moet overal een meter hangen met een aparte registratie voor levering en teruglevering. 

De netbeheerders zullen om die reden opnieuw de slimme meter gaan aanbieden bij de aangeslotenen. Wordt de slimme meter geweigerd of lukt het niet om een andere meter te plaatsen dan ontstaat de verplichting dit te melden bij de Rijksinspectie Digitale Infrastructuur (RDI) op basis van informatie over de meter, de aangeslotene en de klantinteractie.

Er lopen nog gesprekken met verschillende partijen over welke informatie exact moet worden aangeleverd en via welke weg, waarbij op dit moment de Gegevensuitwisselingsentiteit (GUE) als belangrijkste kandidaat wordt gezien door onder andere de RDI zelf. *De informatie uitwisseling zal starten per 1-1-2026.*

== Functionele eisen

Het dataproduct is onderheving aan functionele eisen: wat het dataproduct moet *doen*.

.Functionele eisen
[cols="1, 1, 1"]
|===
|Als Rol |Wil ik |Want

|RDI
|Een uniform overzicht van 'ouderwetse terugdraaimeters' (metergegevens)
|Deze meters moeten vervangen worden 

|RDI
|Een uniform overzicht van de klanten die deze meters gebruiken (aansluitingsgegevens)
|Deze aangeslotenen moeten hun meter laten vervangen

|RDI
|Een uniform overzicht met contactgegevens van deze aangeslotenen (klantcontactgegevens)
|Deze aangeslotenen moeten aangeschreven worden

|RDI
|Een uniform overzicht van de interactie (communicatie) met deze aangeslotenen (klantinteractiegegevens)
|Ik wil weten wat de status van de meterwissel is

|RDI
|Een uniform overzicht van de eigenschappen van de meter (metergegevens)
|Ik wil een geschikte vervangende meter aanbieden

|===

== Dataservice

Er moet gekozen worden tussen een tweetal scenario's: centraal en decentraal. 

* In het centrale scenario verzamelt en integreert EDSN alle datasets en biedt het aan als één dataset (meterwisselgegevens);
* In het decentrale scenario biedt elke regionale netbeheerder haar eigen dataset aan en zullen deze datasets nog verrijkt moeten worden met klantgegevens.

=== Gebruiksscenario: centraal dataproduct

.Gebruiksscenario
[d2,svg,theme=4]
----
shape: sequence_diagram

vars: {
  d2-config: {
    pad: 20
  }
}

Rijksinspectie\nDigitale Infrastructuur
"EDSN\n "
Regionale\nnetbeheerder
Aangeslotene\nRegister

Rijksinspectie\nDigitale Infrastructuur -> "EDSN\n ": 1. Verzoek meterwisselgegevens

"EDSN\n " -> Regionale\nnetbeheerder: 2. Verzoek metergegevens
"EDSN\n " -> Aangeslotene\nRegister: 3. Verzoek aangeslotenegegevens
"EDSN\n " -> Regionale\nnetbeheerder: 4. Verzoek klantinteractiegegevens

Regionale\nnetbeheerder -> "EDSN\n ": 5. Lever metergegevens
Aangeslotene\nRegister -> "EDSN\n ": 6. Lever aangeslotenegegevens
Regionale\nnetbeheerder -> "EDSN\n ": 7. Lever klantinteractiegegevens

"EDSN\n " -> "EDSN\n ": 8. Integreer gegevens

"EDSN\n " -> Rijksinspectie\nDigitale Infrastructuur: 9. Lever meterwisselgegevens

----

1. De RDI verzoekt om meterwisselgegevens 
2. EDSN verzoekt om metergegevens van ouderwetse terugdraaimeter
3. EDSN verzoekt om aangeslotenengegevens (aansluitingsgegevens en klantcontactgegevens)
4. EDSN verzoekt om klantinteractiegegevens
5. De RNB levert metergegevens
6. Het Aangeslotene Register levert aangeslotenegegevens (aansluitingsgegevens en klancontactgegevens)
7. De RNB levert klantinteractiegegevens
8. EDSN combineert de metergegevens, klantinteratiegegevens en de aangeslotnegegevens tot meterwisselgegevens
9. EDSN levert meterwisselgegevens


=== Gebruiksscenario: decentraal dataproduct

.Gebruiksscenario
[d2,svg,theme=4]
----
shape: sequence_diagram

vars: {
  d2-config: {
    pad: 20
  }
}

Rijksinspectie\nDigitale Infrastructuur
Regionale\nnetbeheerder
Aangeslotene\nRegister

Rijksinspectie\nDigitale Infrastructuur -> Regionale\nnetbeheerder: 1. Verzoek metergegevens
Rijksinspectie\nDigitale Infrastructuur -> Aangeslotene\nRegister: 2. Verzoek aangeslotenegegevens
Rijksinspectie\nDigitale Infrastructuur -> Regionale\nnetbeheerder: 3. Verzoek klantinteractiegegevens

Regionale\nnetbeheerder -> Rijksinspectie\nDigitale Infrastructuur: 4. Lever metergegevens
Aangeslotene\nRegister -> Rijksinspectie\nDigitale Infrastructuur: 5. Lever aangeslotenegegevens
Regionale\nnetbeheerder -> Rijksinspectie\nDigitale Infrastructuur: 6. Lever klantinteractiegegevens

Rijksinspectie\nDigitale Infrastructuur -> Rijksinspectie\nDigitale Infrastructuur: 7. Integreer gegevens

----

1. De RDI verzoekt om metergegevens van ouderwetse terugdraaimeter
2. De RDI verzoekt om aangeslotenengegevens (aansluitingsgegevens en klantcontactgegevens)
3. De RDI verzoekt om klantinteractiegegevens
4. De RNB levert metergegevens
5. Het Aangeslotene Register levert aangeslotenegegevens (aansluitingsgegevens en klancontactgegevens)
6. De RNB levert klantinteractiegegevens
7. De RDI combineert de metergegevens, klantinteratiegegevens en de aangeslotnegegevens tot meterwisselgegevens

=== Architectuur

Vanuit architectuurperspectief zijn de volgende keuzes gemaakt:

.Architectuur
[d2,svg,theme=4, width=100%]
----

vars: {
  d2-config: {
    pad: 20
  }
}

grid-rows: 3
grid-columns: 2

vertical-gap: 80
horizontal-gap: 160

RNB.class: noun
EL.class: noun

2_1.class: invisible
AR.class: noun

RDI.class: noun
3_2.class: invisible

RNB -> AR: serves (aansluit)
RNB <-> RDI: " \nserves (opdracht)\n \nserves(klant, metering)\n "
EL -> AR: serves (klant)
AR -> RDI: serves (aangeslotene)

"""

legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  business_color: "" {
    style: {
      fill: "#ffffaf"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  business_text: "Business" {
    shape: text
  }
  application_color: "" {
    style: {
      fill: "#afffff"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  application_text: "Application" {
    shape: text
  }
  technology_color: "" {
    style: {
      fill: "#afffaf"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  technology_text: "Technology" {
    shape: text
  }
}

"""

classes: {
  *: {
    style: {
      shadow: true
    }
  }
  empty: {
    label: ""
    style: {
      fill: transparent
      stroke-width: 0
    }
  }
  verb: {
    style: {border-radius: 30}
  }
  noun: {
    style: {border-radius: 4}
  }
  artifact: {shape: page}
  business: {
    style: {
      fill: "#ffffaf"
    }
  }
  application: {
    style: {
      fill: "#afffff"
    }
  }
  technology: {
    style: {
      fill: "#afffaf"
    }
  }
  invisible: {
    style.opacity: 0
    label: ""
  }
}

----

1. De structuur van de dataset is gebaseerd op het _Begrippenmodel NBNL_ en het _Common Information Model_;
2. Aanlevering van de dataset vanuit de energieleverancier, de regionale netbeheerder, het aangeslotene register en de Rijksinspectie Digitale Infrastructuur geschiedt via JSON-bestanden

== Dataset

=== Volume, variety, veracity, velocity

[NOTE]
====
include::partial$four_v.adoc[]
====

Er zijn maar liefst vijf verschillende datasets, ieder met haar eigen _volume_, _variety_, _veracity_ en _velocity_.

==== Klantgegevens
[cols="1, 3"]
|===
|Type |Beschrijving

|Volume
|Laag, na de initiële verlading volgen alleen maar incrementele verladingen

|Variety
|Gestructureerd

|Veracity
|Hoog, de dataset wordt samengesteld uit brongegevens die ook voor facturatie worden ingezet

|Velocity
|Laag, na de initiële verlading volgen alleen maar incrementele verladingen
|===

==== Aansluitingengegevens
[cols="1, 3"]
|===
|Type |Beschrijving

|Volume
|Laag, na de initiële verlading volgen alleen maar incrementele verladingen

|Variety
|Gestructureerd

|Veracity
|Hoog

|Velocity
|Laag, na de initiële verlading volgen alleen maar incrementele verladingen
|===

==== Aangeslotenegegevens
[cols="1, 3"]
|===
|Type |Beschrijving

|Volume
|Laag, na de initiële verlading volgen alleen maar incrementele verladingen

|Variety
|Gestructureerd

|Veracity
|Hoog

|Velocity
|Laag, na de initiële verlading volgen alleen maar incrementele verladingen
|===

==== Klantinteractiegegevens
[cols="1, 3"]
|===
|Type |Beschrijving

|Volume
|Laag, na de initiële verlading volgen alleen maar incrementele verladingen

|Variety
|Gestructureerd

|Veracity
|Hoog

|Velocity
|Laag, na de initiële verlading volgen alleen maar incrementele verladingen
|===

==== Meteringegevens
[cols="1, 3"]
|===
|Type |Beschrijving

|Volume
|Laag, na de initiële verlading volgen alleen maar incrementele verladingen

|Variety
|Gestructureerd

|Veracity
|Hoog

|Velocity
|Laag, na de initiële verlading volgen alleen maar incrementele verladingen
|===

== Voorwaarden

Bij elke dataset hoort precies één dataproduct. 

1. Het dataproduct behorende bij de dataset klantgegevens wordt als gesloten data aangeboden.
2. Het dataproduct behorende bij de dataset aansluitingengegevens wordt als gesloten data aangeboden.
3. Het dataproduct behorende bij de dataset aangeslotenegegevens wordt als gesloten data aangeboden.
4. Het dataproduct behorende bij de dataset klantinteractiegegevens wordt als gesloten data aangeboden.
5. Het dataproduct behorende bij de dataset meteringegevens wordt als gesloten data aangeboden.

== Beslissingen en aannames

[cols="1, 1"]
|===
|Type |Beschrijving

|Aanname
|De meterwisselopdracht is geen dataproduct, maar een opdracht van de RDI aan de RNB's

|Aanname
|Er is doel/binding voor alle dataproducten

|Aanname
|Het Aangeslotene Register kan de klantgegevens en de aansluitingengegevens opslaan en doorgeven

|Aanname
|Klantgegevens en aansluitingengegevens kunnen gekoppeld worden

|Aanname
|Aangeslotenegegevens, klantinteractiegegevens en meteringgegevens kunnen gekoppeld worden

|Aanname
|De datasets worden niet als open datasets gepubliceerd

|Aanname
|De dataverlading incrementeel

|Aanname
|De aansluitingengegevens die de RNB's aanleveren bevatten alleen gegevens van aansluitingen met een  'ouderwetse terugdraaimeter'. Dus niet _verzenden en dan filteren_, maar _filteren en dan verzenden_. Idem voor klantinteractiegegevens en meteringegevens

|Beslissing
|Bij elke dataset hoort precies één dataproduct

|===
