= Rijksinpsectie Data Infrastructuur (RDI) Data delen

Dit ontwerp beschrijft het beoogde gebruiksscenario voor het dataproduct
_RDI_, alsmede de achterliggende architectuur en gemaakte keuzes.

[NOTE]
====
include::partial$data_product.adoc[]
====

== Reikwijdte

Per 1-1-2027 wordt de salderingsregeling afgeschaft. Klanten die op dat moment nog een ouderwetse terugdraaimeter hebben kunnen dan nog altijd salderen en dat brengt rechtsongelijkheid. Om die reden worden de ouderwetse terugdraaimeters verboden en moet overal een meter hangen met een aparte registratie voor levering en teruglevering. 

De netbeheerders zullen om die reden opnieuw de slimme meter gaan aanbieden bij de aangeslotenen. Wordt de slimme meter geweigerd of lukt het niet om een andere meter te plaatsen dan ontstaat de verplichting dit te melden bij de RDI obv de gegevens zoals hiernaast vermeld.

Er lopen nog gesprekken met verschillende partijen over welke informatie exact moet worden aangeleverd en via welke weg, waarbij op dit moment de GUE als belangrijkste kandidaat wordt gezien door onder andere de RDI zelf. *De informatie uitwisseling zal starten per 1-1-2026.*

== Functionele eisen

Het dataproduct is onderheving aan functionele eisen: wat het dataproduct moet *doen*.

.Functionele eisen
[cols="1, 1, 1"]
|===
|Als Rol |Wil ik |Want

|Energieleverancier (EL)
|Een uniform overzicht met aansluitingen en contactgegevens van al mijn klanten (klantgegevens)
|Deze informatie moet ik naar het Aangeslotene Register sturen

|Regionale Netbeheerder (RNB)
|Een uniform overzicht met aansluitingengegevens van mijn aangeslotenen
|Deze informatie moet ik naar het Aangeslotene Register sturen

|Regionale Netbeheerder (RNB)
|Een uniform overzicht met klantinteractiegegevens van mijn aangeslotenen met een 'ouderwetse terugdraaimeter'
|Deze informatie moet ik naar de Rijksinspectie Digitale Infrastructuur sturen

|Regionale Netbeheerder (RNB)
|Een uniform overzicht met meteringegevens van mijn aangeslotenen met een 'ouderwetse terugdraaimeter'
|Deze informatie moet ik naar de Rijksinspectie Digitale Infrastructuur sturen

|Aangeslotene Register (AR)
|Een uniform overzicht met aansluitingen en contactgegevens van al mijn klanten met een 'ouderwetse terugdraaimeter' (aangeslotenegegevens)
|Deze informatie moet ik naar de Rijksinspectie Digitale Infrastructuur sturen

|Rijksinspectie Digitale Infrastructuur (RDI)
|Een uniform overzicht met aansluitingen en contactgegevens van alle aangeslotenen met een 'ouderwetse terugdraaimeter'
|Ik wens de netbeheerder te instrueren van deze aangesloten de meter te vervangen 

|===

== Dataservice

=== Gebruiksscenario

Het volgende gebruiksscenario wordt ondersteund:

.Gebruiksscenario
[d2,svg,theme=4]
----
shape: sequence_diagram

vars: {
  d2-config: {
    pad: 20
  }
}

EL
RNB
AR
RDI

EL -> AR: 1. Lever dataset\: klantgegevens
RNB -> AR: 2. Lever dataset\: aansluitingengegevens
AR -> RDI: 3. Lever dataset\: aangeslotenegegevens
RNB -> RDI: 4. Lever dataset\: klantinteractiegegevens
RNB -> RDI: 5. Lever dataset\: meteringegevens
RDI -> RNB: 6. Meterwisselopdracht
----

1. De energieleverancier levert klantgegevens
2. De regionale netbeheerder levert aansluitingsgegevens
3. Het aangeslotene register levert aangeslotenegegevens
4. De regionale netbeheerder levert klantinteractiegegevens
5. De regionale netbeheerder levert meteringgegevens
6. De Rijksinspectie Digitale Infrastructuur geeft opdracht tot het vervangen van de 'ouderwetse terugdraaimeter''

=== Architectuur

Vanuit architectuurperspectief zijn de volgende keuzes gemaakt:

.Architectuur
[d2,svg,theme=4,scaledwidth=100%]
----

vars: {
  d2-config: {
    pad: 20
  }
}

grid-rows: 3
grid-columns: 2

vertical-gap: 80
horizontal-gap: 160

RNB.class: noun
EL.class: noun

2_1.class: invisible
AR.class: noun

RDI.class: noun
3_2.class: invisible

RNB -> AR: serves (aansluit)
RNB <-> RDI: " \nserves (opdracht)\n \nserves(klant, metering)\n "
EL -> AR: serves (klant)
AR -> RDI: serves (aangeslotene)

"""

legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  business_color: "" {
    style: {
      fill: "#ffffaf"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  business_text: "Business" {
    shape: text
  }
  application_color: "" {
    style: {
      fill: "#afffff"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  application_text: "Application" {
    shape: text
  }
  technology_color: "" {
    style: {
      fill: "#afffaf"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  technology_text: "Technology" {
    shape: text
  }
}

"""

classes: {
  *: {
    style: {
      shadow: true
    }
  }
  empty: {
    label: ""
    style: {
      fill: transparent
      stroke-width: 0
    }
  }
  verb: {
    style: {border-radius: 30}
  }
  noun: {
    style: {border-radius: 4}
  }
  artifact: {shape: page}
  business: {
    style: {
      fill: "#ffffaf"
    }
  }
  application: {
    style: {
      fill: "#afffff"
    }
  }
  technology: {
    style: {
      fill: "#afffaf"
    }
  }
  invisible: {
    style.opacity: 0
    label: ""
  }
}

----

1. De structuur van de dataset is gebaseerd op het _Begrippenmodel NBNL_ en het _Common Information Model_;
2. Aanlevering van de dataset vanuit de energieleverancier, de regionale netbeheerder, het aangeslotene register en de Rijksinspectie Digitale Infrastructuur geschiedt via JSON-bestanden

== Dataset

=== Volume, variety, veracity, velocity

[NOTE]
====
include::partial$four_v.adoc[]
====

Er zijn maar liefst vijf verschillende datasets, ieder met haar eigen _volume_, _variety_, _veracity_ en _velocity_.

==== Klantgegevens
[cols="1, 3"]
|===
|Type |Beschrijving

|Volume
|Laag, na de initiële verlading volgen alleen maar incrementele verladingen

|Variety
|Gestructureerd

|Veracity
|Hoog, de dataset wordt samengesteld uit brongegevens die ook voor facturatie worden ingezet

|Velocity
|Laag, na de initiële verlading volgen alleen maar incrementele verladingen
|===

==== Aansluitingengegevens
[cols="1, 3"]
|===
|Type |Beschrijving

|Volume
|Laag, na de initiële verlading volgen alleen maar incrementele verladingen

|Variety
|Gestructureerd

|Veracity
|Hoog

|Velocity
|Laag, na de initiële verlading volgen alleen maar incrementele verladingen
|===

==== Aangeslotenegegevens
[cols="1, 3"]
|===
|Type |Beschrijving

|Volume
|Laag, na de initiële verlading volgen alleen maar incrementele verladingen

|Variety
|Gestructureerd

|Veracity
|Hoog

|Velocity
|Laag, na de initiële verlading volgen alleen maar incrementele verladingen
|===

==== Klantinteractiegegevens
[cols="1, 3"]
|===
|Type |Beschrijving

|Volume
|Laag, na de initiële verlading volgen alleen maar incrementele verladingen

|Variety
|Gestructureerd

|Veracity
|Hoog

|Velocity
|Laag, na de initiële verlading volgen alleen maar incrementele verladingen
|===

==== Meteringegevens
[cols="1, 3"]
|===
|Type |Beschrijving

|Volume
|Laag, na de initiële verlading volgen alleen maar incrementele verladingen

|Variety
|Gestructureerd

|Veracity
|Hoog

|Velocity
|Laag, na de initiële verlading volgen alleen maar incrementele verladingen
|===

== Voorwaarden

Bij elke dataset hoort precies één dataproduct. 

1. Het dataproduct behorende bij de dataset klantgegevens wordt als gesloten data aangeboden.
2. Het dataproduct behorende bij de dataset aansluitingengegevens wordt als gesloten data aangeboden.
3. Het dataproduct behorende bij de dataset aangeslotenegegevens wordt als gesloten data aangeboden.
4. Het dataproduct behorende bij de dataset klantinteractiegegevens wordt als gesloten data aangeboden.
5. Het dataproduct behorende bij de dataset meteringegevens wordt als gesloten data aangeboden.

== Beslissingen en aannames

[cols="1, 1"]
|===
|Type |Beschrijving

|Aanname
|De meterwisselopdracht is geen dataproduct, maar een opdracht van de RDI aan de RNB's

|Aanname
|Er is doel/binding voor alle dataproducten

|Aanname
|Het Aangeslotene Register kan de klantgegevens en de aansluitingengegevens opslaan en doorgeven

|Aanname
|Klantgegevens en aansluitingengegevens kunnen gekoppeld worden

|Aanname
|Aangeslotenegegevens, klantinteractiegegevens en meteringgegevens kunnen gekoppeld worden

|Aanname
|De datasets worden niet als open datasets gepubliceerd

|Aanname
|De dataverlading incrementeel

|Aanname
|De aansluitingengegevens die de RNB's aanleveren bevatten alleen gegevens van aansluitingen met een  'ouderwetse terugdraaimeter'. Dus niet _verzenden en dan filteren_, maar _filteren en dan verzenden_. Idem voor klantinteractiegegevens en meteringegevens

|Beslissing
|Bij elke dataset hoort precies één dataproduct

|===
