= Realisatie Dataproducten
:page-title: Realisatie van Dataproducten
:page-nav-title: Dataproducten

== Executive Summary

Dit document beschrijft de belemmeringen in het proces voor het realiseren van
dataproducten door Themateam Datadelen. Om te versnellen wordt er voorgesteld
gebruik te maken van dataproducten beheerd door Kernteam Netdigitalisering,
vanuit Domeinraad S&I. Deze dataproducten zijn echter nog niet beschikbaar,
waardoor op de korte termijn wordt ingezet op het sneller ontsluiten van
dataproducten. De focus ligt hierbij  op het verbeteren van governance,
businesscase en mandaat.

== Doel

Het doel van dit document is om de concrete stappen en acties te beschrijven
voor het realiseren van dataproducten door Themateam Datadelen, met nadruk op
korte-termijnacties die nodig zijn om governance, businesscase en mandaat vast
te leggen. Deze acties vormen de basis voor de verdere ontwikkeling van
dataproducten in 2026 en 2027.

== Achtergrond

Vanuit *Werkgroep TSO/DSO-interface* (onderdeel van *Kernteam
Netdigitalisering*, *Domeinraad S&I*) worden meerdere dataproducten ontsloten
met S&I data (connectiviteit, geolokatie, topologie, *steady state* en
*operations*). Deze dataproducten kunnen als basis dienen voor dataproducten
(te) realiseren door Themateam Datadelen.

Er wordt momenteel beperkte voortgang geboekt bij het realiseren van
dataproducten door Themateam Datadelen, waarbij het hergebruiken van
dataproducten vanuit S&I een versnelling kan opleveren.

== Analyse

Deze analyse is gebaseerd op aannames vanuit Themateam Datadelen. Voor een
volledige beoordeling is overleg met externe stakeholders noodzakelijk.

|===
| Nr | Aspect | Observatie / Uitdaging | Implicatie

| 1
| Eigenaarschap
| Onvoldoende eigenaarschap voor dataproducten, vanuit de netbeheerders
| Noodzaak voor duidelijke verantwoordelijkheden

| 2
| Bestuur en mandaat
| Het mandaat van de netbeheerder is onvoldoende vastgelegd
| Acteerbaar mandaat voor dataproducten uitvoeren. Hier ligt een rol voor het
  Data Lead Team, Programma LAN en CDOs. Al deze stakeholders dienen een
  actieve rol (kampioen) in het voorbrengingsproces te hebben

| 3
| Weerstand
| Beperkingen door traditionele werkwijzen en beperkte expertise
| Draagvlak creëren via concrete voorbeelden en inhoudelijk opleiden binnen de
  domeinen architectuur en data

| 4
| Klantgerichtheid
| Onvoldoende klantwaarde in bestaande en voorgestelde dataproducten
| Dataproducten moeten direct aantoonbare waarde opleveren, betrek klanten in
  een vroeg stadium om de druk voor implementatie op te voeren

| 5
| Businesscase
| De waarde van dataproducten is niet (voldoende) aantoonbaar
| De businesscase moet expliciet worden gedefinieerd, uitgedragen en doorleefd

| 6
| Prioritering
| Waarde van externe input wordt onvoldoende erkend
| Betere prioritering met testcases en stakeholders, ondersteunen met
  businesscase
|===

== Tijdspad en Acties

**Kortetermijn (0–6 maanden)**

De focus ligt in deze fase op het expliciet maken van *governance*, *mandaat*
en *businesscase*. Dit omvat:

* Vastleggen van en sturen op governance en mandaat (knelpunten 1, 2).
* Het ontwikkelen van een businesscase en prioriteiten, in samenspraak met de
klant (knelpunten 5, 6).
* Voorbereiden van processen en documentatie voor de langere termijn
(knelpunten 3, 5).

**Middenlangetermijn (6–18 maanden)**

De eerste S&I-dataproducten en implementerende teams worden decentraal
gerealiseerd:

* aansluiten bij nieuw gerealiseerde teams bij de netbeheerders, voor
implementatie van dataproducten voor Themateam Datadelen.
* nadruk op synergie: zoek overlap tussen functionele eisen zowel voor
Themateam Datadelen als Kernteam Netdigitalisering van toepassing zijn.
* Testen en evalueren van de eerste dataproducten (knelpunten 3, 5).
* Verbeteren van klantwaarde door het ontwikkelen van een product dat voldoet
aan de behoeften van externe stakeholders (knelpunt 5).

**Langetermijn (18+ maanden)**

Het proces wordt volledig opgeschaald en geoptimaliseerd:

* Continue verbetering van S&I-dataproducten (knelpunten 1–7).
* Teams bij netbeheerders worden niet direct meer benaderd, gewenste
functionaliteit wordt gevraagd aan en geïmplementeerd door Kernteam
Netdigitalisering.
* Optimalisatie van kwaliteit, traceerbaarheid en klantwaarde.

== Continue verbeteren

Na de initiële implementatie van de eerste dataproducten, moet er een evaluatie
plaatsvinden van de governance, businesscase en mandaat. Op basis van de
evaluatie kunnen verdere optimalisaties en verbeteringen worden doorgevoerd om
het proces en de dataproducten continu te verbeteren.
