= Rijksinspectie Data Infrastructuur (RDI)

Dit ontwerp beschrijft het beoogde gebruiksscenario voor de dataproducten _Klantcontact_ en _Aangeslotene_, alsmede hun achterliggende architectuur en de gemaakte keuzes. 

[NOTE]
====
include::partial$data_product.adoc[]
====

== Reikwijdte

Per 1 januari 2027 wordt de salderingsregeling afgeschaft. Klanten die op dat moment nog een 'ouderwetse terugdraaimeter' hebben kunnen dan nog altijd salderen en dat brengt rechtsongelijkheid. Om die reden worden de ouderwetse terugdraaimeters verboden en moet overal een meter hangen met een aparte registratie voor levering en teruglevering. 

Daarom moeten de netbeheerder vanaf 1 januari 2026 binnen 2 jaar al deze meters hebben gewisseld. Hiervoor dienen de netbeheerders deze klanten tweemaal een aanbiedingsbrief te sturen. Indien dit na twee brieven en vervolgens 10 weken niet heeft geresulteerd in een plaatsing, dienen de netbeheerders het dossier over te dragen aan de Rijksinspectie Digitale Infrastructuur (RDI). Deze gaat vervolgens handhaven.

== Functionele eisen

Het dataproduct moet voldoen aan functionele eisen; deze vertellen wie ("*Als rol*") welke data ("*Wil ik*") nodig heeft en waarom ("*Want*").

.Functionele eisen
[cols="1, 1, 1"]
|===
|Als rol |Wil ik |Want

|Regionale Netbeheerder (RNB)
|Een uniform overzicht van klantcontactgegevens van klanten met een 'ouderwetse terugdraaimeter'
|Ik moet weten welke klanten ik een aanbiedingsbrief moet sturen

|Regionale Netbeheerder (RNB)
|Een uniform overzicht van aangslotenegegevens van mijn klanten met een 'ouderwetse terugdraaimeter'
|Ik moet weten waar ik de aanbiedingsbrief naartoe moet sturen

|Rijksinspectie Digitale Infrastructuur (RDI)
|Een integratie van klantcontactgegevens, aangeslotenegegevens, metergegevens en klantinteractiegegevens: meterwisseldossier
|Ik moet handhaven

|===

== Dataservice

Er is gekozen voor een decentraal scenario waarbij elke regionale netbeheerder (RNB) zelf de aangeslotene met een ouderwetse terugdraaimeter aanschrijft. Een RNB kan ontbrekende gegevens, zoals klantcontactgegevens en aangeslotenegegevens, opvragen bij de Gegevensuitwisselingsentiteit (GUE). De GUE treedt op als intermediair tussen de RNB en de Energieleverancier (EL) en het Aangesloteneregister (AR).

Het gaat om twee datasets, _klantcontactgegevens_ en _aangeslotenegegevens_, die samen met _metergegevens_ en  _klantinteractiegegevens_ geïntegreerd moeten worden tot één dataset: _meterwisselgegevens_.


=== Gebruiksscenario

.Gebruiksscenario 
[d2,svg,theme=4]
----

vars: {
  d2-config: {
    pad: 20
  }
}

Decentraal scenario: {
	shape: sequence_diagram
	RNB: "Regionale\nNetbeheerder\n(RNB)"
	GUE: "Gegevensuit-\nwisselentiteit\n(GUE)"
	EL:  "Energie-\nleverancier\n(EL)"
	AR:  "Aangeslotene\nRegister\n(AR)"
	A:   "Aangeslotene\n(A)\n "
	RDI: "Rijksinspectie\nDigitale Infrastructuur\n(RDI)"

	RNB -> GUE:  1. Verzoek om klantcontactgegevens
	GUE -> EL:   2. Verzoek om klantcontactgegevens
	EL -> GUE:   3. Levering klantcontactgegevens
	GUE -> RNB:  4. Levering klantcontactgegevens
	RNB -> GUE:  5. Verzoek aangeslotenegegevens
	GUE -> AR:   6. Verzoek aangeslotenegegevens
	AR -> GUE:   7. Levering aangeslotenegegevens
	GUE -> RNB:  8. Levering aangeslotenegegevens
	RNB -> RNB:  9. Integreer klantcontact-, aangeslotene- en \nklantinteractiegegevens tot meterwisselgegevens
	RNB -> A:   10. Verstuur aanbiedingsbrieven
	A -> RNB:   11. Reactie aanbiedingsbrieven
	RNB -> RNB: 12. Maak meterwisseldossier
	RNB -> RDI: 13. Verstuur meterwisseldossier
}

----

 1. Een RNB verzoekt het GUE om contactgegevens van een klant met een ouderwetse terugdraaimeter
 2. Het GUE verzoekt de Energieleverancier om de klantcontactgegevens
 3. De Energieleverancier levert de klantcontactgegevens aan het GUE
 4. Het GUE levert de klantcontactgegevens aan de RNB
 5. De RNB weet nu welke klant is aangesloten op de ouderwetse terugdraaimeter en vraagt het GUE om aangeslotenegegevens
 6. Het GUE verzoekt het Aangeslotene Register om aangeslotenegegevens
 7. Het Aangeslotene Register levert de aangeslotenegegevens aan de GUE
 8. Het GUE levert de aangeslotenegegevens aan de RNB
 9. De RNB integreert de ontvangen klantcontact- en aangeslotenegegevens met haar eigen metergegevens- en klantinteractiegegevens tot meterwisselgegevens
10. De RNB verstuurt (tot twee keer toe) aanbiedingsbrieven aan de aangslotene met een ouderwetse terugdraaimeter
11. De aangesloten reageert op de aanbiedingsbrieven
12. De RNB maakt een meterwisseldossier
13. De RNB verstuurt het meterwisseldossier naar de RDI zodat deze kan handhaven

=== Architectuur

Vanuit architectuurperspectief zijn de volgende keuzes gemaakt:

.Architectuur
[d2,svg,theme=4]
----

vars: {
  d2-config: {
    pad: 20
  }
}

grid-rows: 5
grid-columns: 3

vertical-gap: 80
horizontal-gap: 160

1_1.class: empty
RNB.class: [noun; business]
RDI.class: [noun; business]

Extract.class: [verb; business]
Transform.class: [verb; business]
Load.class: [verb; business]

3_1.class: empty
Datamart: {
  label: Datamart\n(Meter\nKlantinteractie)
  class: [noun; application]
}
3_3.class: empty

DP_Klantcontact: {
  label: Dataproduct\nKlantcontact
  class: [noun; application]
}
"File gateway".class: [noun; application]
DP_Aangeslotene: {
  label: Dataproduct\nAangeslotene
  class: [noun; application]
}

"JSON File1": {
  label: JSON File\nKlantcontact
  class: [artifact; technology]
}
5_2.class: empty
"JSON File2": {
  label: JSON File\nAangeslotene
  class: [artifact; technology]
}

RNB -> Extract: "assigned to"
RNB -> Transform: "assigned to"
RNB -> Load: "assigned to"

Extract -> Transform: "triggers"
Transform -> Load: "triggers"
Load -> RDI: "serving"

Datamart -> Transform: "serving"
Datamart -> Load: "serving"

DP_Klantcontact -> Extract: "serving"
"File gateway" -> DP_Klantcontact: "accesses (read)"
"File gateway" -> DP_Aangeslotene: "accesses (read)"
DP_Aangeslotene -> Load: "serving"

"JSON File1" -> DP_Klantcontact: "realises"
"JSON File2" -> DP_Aangeslotene: "realises"

legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  business_color: "" {
    style: {
      fill: "#ffffaf"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  business_text: "Business" {
    shape: text
  }
  application_color: "" {
    style: {
      fill: "#afffff"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  application_text: "Application" {
    shape: text
  }
  technology_color: "" {
    style: {
      fill: "#afffaf"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  technology_text: "Technology" {
    shape: text
  }
}

classes: {
  *: {
    style: {
      shadow: true
    }
  }
  empty: {
    label: ""
    style: {
      fill: transparent
      stroke-width: 0
    }
  }
  verb: {
    style: {border-radius: 30}
  }
  noun: {
    style: {border-radius: 4}
  }
  artifact: {shape: page}
  business: {
    style: {
      fill: "#ffffaf"
    }
  }
  application: {
    style: {
      fill: "#afffff"
    }
  }
  technology: {
    style: {
      fill: "#afffaf"
    }
  }
}

----


1. De structuur van de dataset is gebaseerd op het _Begrippenmodel NBNL_ en het _Common Information Model_
2. Aanlevering van de klantcontactgegevens en de aangeslotenegegevens geschiedt met JSON-bestanden
3. Aanlevering van het meterwisseldossier vanuit de netbeheerder naar de RDI geschiedt met JSON-bestand

== Dataset

=== Volume, variety, veracity, velocity

[NOTE]
====
include::partial$four_v.adoc[]
====

In scenario zijn er twee verschillende dataproducten, _Klantcontact_ en _Aangeslotene_, elk met hun eigen dataset en elke dataset heeft haar eigen kenmerken:

==== Dataset _Klantcontact_

[cols="1, 3"]
|===
|Type |Beschrijving

|Volume
|Laag, < 100MB (ongecomprimeerd)

|Variety
|Gestructureerd

|Veracity
|Midden

|Velocity
|Laag
|===

==== Dataset _Aangeslotene_

[cols="1, 3"]
|===
|Type |Beschrijving

|Volume
|Laag, < 100MB (ongecomprimeerd)

|Variety
|Gestructureerd

|Veracity
|Hoog

|Velocity
|Laag
|===

== Voorwaarden

Dit dataproduct wordt als _gesloten data_ aangeboden, onder de grondslag _Wettelijke verplichting_.


== Beslissingen en aannames

[cols="1, 1"]
|===
|Type |Beschrijving

|Beslissing
|Er is gekozen voor het decentrale scenario waarbij elke RNB de benodigde gegevens bij de GUE opvraagt

|Aanname
|Het GUE regelt (eventuele) autorisatie en authenticatie

|Aanname
|Het Aangeslotene Register kan de aangeslotenegegevens leveren en deze kunnen gekoppeld worden

|Aanname
|De Energieleverancier kan de klantcontactgegevens leveren en deze kunnen gekoppeld worden

|Aanname
|Klantcontactgegevens, aangslotenegegevens, metergegevens en klantinteractiegegevens kunnen gekoppeld worden

|Aanname
|De RNB's kunnen de klanten met een 'ouderwetse terugdraaimeter' herkennen, zodat zij alleen van deze klanten gegevens opvragen

|Aanname
|Het betreft uitsluitend KV-klanten; GV-klanten hebben geen salderingsregeling (maar misschien wel een ouderwetse terugdraaimeter)

|Aanname
|Een RNB kan meerdere keren aan het GUE vragen om klantcontactgegevens. Zowel van dezelfde klant als van verschillende klanten

|Beslissing
|Het GUE levert de ontvangen gegevens (klantcontact en aangeslotene) ongewijzigd door aan de RNB

|Aanname
|De GUE is in staat de gevraagde gegevens tijdig te leveren

|Aanname
|De aangeslotene is de contactpersoon voor de aansluiting behorende bij de ouderwetse terugdraaimeter en kan (laten) beslissen of deze meter vervangen wordt door een slimme meter

|===
