= Rijksinspectie Data Infrastructuur (RDI)

Dit ontwerp beschrijft het beoogde gebruiksscenario voor de dataproducten _RDI_ en _Klantinteractie_, alsmede hun achterliggende architectuur en de gemaakte keuzes. 

- Dataproduct _RDI_ bevat als dataset klantcontactgegevens en aansluitingsgegevens;
- Dataproduct _Klantinteractie_ bevat als dataset klantinteractiegegevens en metergegevens. 



[NOTE]
====
include::partial$data_product.adoc[]
====

== Reikwijdte

Per 1-1-2027 wordt de salderingsregeling afgeschaft. Klanten die op dat moment nog een ouderwetse terugdraaimeter hebben kunnen dan nog altijd salderen en dat brengt rechtsongelijkheid. Om die reden worden de ouderwetse terugdraaimeters verboden en moet overal een meter hangen met een aparte registratie voor levering en teruglevering. 

De netbeheerders zullen om die reden opnieuw de slimme meter gaan aanbieden bij de aangeslotenen. Wordt de slimme meter geweigerd of lukt het niet om een andere meter te plaatsen dan ontstaat de verplichting dit te melden bij de Rijksinspectie Digitale Infrastructuur (RDI) op basis van informatie over de meter, de aangeslotene en de klantinteractie.

Er lopen nog gesprekken met verschillende partijen over welke informatie exact moet worden aangeleverd en via welke weg, waarbij op dit moment de Gegevensuitwisselingsentiteit (GUE) als belangrijkste kandidaat wordt gezien door onder andere de RDI zelf. *De informatie uitwisseling zal starten per 1-1-2026.*

== Functionele eisen

Het dataproduct moet voldoen aan functionele eisen; deze vertellen wie ("*Als rol*") welke data ("*Wil ik*") nodig heeft en waarom ("*Want*").

.Functionele eisen
[cols="1, 1, 1"]
|===
|Als rol |Wil ik |Want

|Rijksinspectie Digitale Infrastructuur (RDI)
|Een uniform overzicht van 'ouderwetse terugdraaimeters' (metergegevens)
|Deze meters moeten vervangen worden 

|Rijksinspectie Digitale Infrastructuur (RDI)
|Een uniform overzicht van de klanten die deze meters gebruiken (aangeslotenegegevens)
|Deze aangeslotenen moeten hun meter laten vervangen

|Rijksinspectie Digitale Infrastructuur (RDI)
|Een uniform overzicht met contactgegevens van deze aangeslotenen (klantcontactgegevens)
|Deze aangeslotenen moeten aangeschreven worden

|Rijksinspectie Digitale Infrastructuur (RDI)
|Een uniform overzicht van de interactie (communicatie) met deze aangeslotenen (klantinteractiegegevens)
|Ik wil weten wat de status van de meterwissel is

|Rijksinspectie Digitale Infrastructuur (RDI)
|Een integratie van metergegevens, aangeslotenegegevens, klantcontactgegevens en klantinteractiegegevens
|Ik wil de integratie van deze gegevens: meterwisselgegevens

|===

== Dataservice

Er moet gekozen worden tussen een tweetal scenario's: _centraal_ en _decentraal_. 

1. In het _centrale scenario_ vraagt de Rijksinspectie Digitale Infrastructuur (RDI) aan EDSN om de meterwisselgegevens. De EDSN vraagt de benodigde gegevens op bij de Regionale Netbeheerders (RNBs) en het Aangeslotene Register (AR) om vervolgens deze gegevens te integreren tot één dataset en te geven aan de RDI;
2. In het _decentrale scenario_ vraagt de RDI de benodigde gegevens zelf op bij elke RNB en bij het AR om vervolgens deze gegevens zelf te integreren tot één dataset.

In beide scenario's gaat het om twee datasets, _klantinteractiegegevens_ en _aangeslotenegegevens_, die geïntegreerd moeten worden tot één dataset: _meterwisselgegevens_.

Vanuit doelarchitectuur en om de inspanningen van de RNBs te minimaliseren gaat de voorkeur uit naar het _centrale_ scenario waarin EDSN de benodigde gegevens opvraagt, integreert en beschikbaar stelt. Voorwaarde is wel dat EDSN hiervoor voldoende capaciteit beschikbaar kan stellen.

=== Gebruiksscenario: centraal dataproduct

.Gebruiksscenario centraal dataproduct
[d2,svg,theme=4]
----
shape: sequence_diagram

vars: {
  d2-config: {
    pad: 20
  }
}

RDI:  "Rijksinspectie\nDigitale Infrastructuur\n(RDI)"
EDSN: " \nEDSN\n \n "
RNB:  "Regionale\nNetbeheerder\n(RNB)"
AR:   "Aangeslotene\nRegister\n(AR)"

RDI -> EDSN:   1. Verzoek meterwisselgegevens
EDSN -> RNB:   2. Verzoek metergegevens
RNB -> EDSN:   3. Lever metergegevens
EDSN -> AR:    4. Verzoek aangeslotenegegevens
AR -> EDSN:    5. Lever aangeslotenegegevens
EDSN -> RNB:   6. Verzoek klantinteractiegegevens
RNB -> EDSN:   7. Lever klantinteractiegegevens
EDSN -> EDSN:  8. Integreer gegevens
EDSN -> RDI:   9. Lever meterwisselgegevens

----

1. De RDI verzoekt EDSN om meterwisselgegevens;
2. EDSN verzoekt de RNB om metergegevens van ouderwetse terugdraaimeter;
3. De RNB levert metergegevens aan EDSN;
4. EDSN verzoekt het AR om aangeslotenengegevens (aansluitingsgegevens en klantcontactgegevens) behorende bij deze meters;
5. Het AR levert aangeslotenegegevens (aansluitingsgegevens en klancontactgegevens) aan EDSN;
6. EDSN verzoekt de RNB om klantinteractiegegevens van deze klanten;
7. De RNB levert klantinteractiegegevens aan EDSN;
8. EDSN combineert de metergegevens, klantinteratiegegevens en de aangeslotenegegevens tot meterwisselgegevens;
9. EDSN levert meterwisselgegevens aan de RDI.


=== Gebruiksscenario: decentraal dataproduct

.Gebruiksscenario decentraal dataproduct
[d2,svg,theme=4]
----
shape: sequence_diagram

vars: {
  d2-config: {
    pad: 20
  }
}

RDI: "Rijksinspectie\nDigitale Infrastructuur\n(RDI)"
RNB: "Regionale\nNetbeheerder\n(RNB)"
AR:  "Aangeslotene\nRegister\n(AR)"

RDI -> RNB: 1. Verzoek metergegevens
RNB -> RDI: 2. Lever metergegevens
RDI -> AR:  3. Verzoek aangeslotenegegevens
AR -> RDI:  4. Lever aangeslotenegegevens
RDI -> RNB: 5. Verzoek klantinteractiegegevens
RNB -> RDI: 6. Lever klantinteractiegegevens
RDI -> RDI: 7. Integreer gegevens

----

1. De RDI verzoekt de RNB om metergegevens van ouderwetse terugdraaimeter;
2. De RNB levert metergegevens aan de RDI;
3. De RDI verzoekt de AR om aangeslotenengegevens (aansluitingsgegevens en klantcontactgegevens) behorende bij deze meters;
4. Het AR levert aangeslotenegegevens (aansluitingsgegevens en klancontactgegevens) de RDI;
5. De RDI verzoekt de RNB om klantinteractiegegevens van deze klanten;
6. De RNB levert klantinteractiegegevens aan de RDI;
7. De RDI combineert de metergegevens, klantinteratiegegevens en de aangeslotenegegevens tot meterwisselgegevens.

=== Architectuur

Vanuit architectuurperspectief zijn de volgende keuzes gemaakt:

.Architectuur
[d2,svg,theme=4]
----
vars: {
  d2-config: {
    pad: 20
  }
}

grid-rows: 5
grid-columns: 4

vertical-gap: 80
horizontal-gap: 160

RNB: {
  label: Netbeheerder
  class: [noun; business]
}
1_2.class: empty
EDSN.class: [noun; business]
RDI.class: [noun; business]

2_1.class: empty
Extract.class: [verb; business]
Transform.class: [verb; business]
Load.class: [verb; business]

3_1.class: empty
3_2.class: empty
Datamart.class: [noun; application]
3_4.class: empty

Maatwerk.class: [noun; application]
DP_Klantinteractie: {
  label: Dataproduct\nKlantinteractie
  class: [noun; application]
}
"File gateway".class: [noun; application]
DP_RDI: {
  label: Dataproduct\nRDI
  class: [noun; application]
}

5_1.class: empty
"JSON File1": {
  label: JSON File\nKlantinteractie
  class: [artifact; technology]
}
5_3.class: empty
"JSON File2": {
  label: JSON File\nRDI
  class: [artifact; technology]
}

RNB -> Maatwerk: "assigned to"
EDSN -> Extract: "assigned to"
EDSN -> Transform: "assigned to"
EDSN -> Load: "assigned to"

Extract -> Transform: "triggers"
Transform -> Load: "triggers"
Load -> RDI: "serving"

Datamart -> Transform: "serving"
Datamart -> Load: "serving"

Maatwerk -> DP_Klantinteractie: "accesses (write)"
DP_Klantinteractie -> Extract: "serving"
"File gateway" -> DP_Klantinteractie: "accesses (read)"
"File gateway" -> DP_RDI: "accesses (read)"
DP_RDI -> Load: "serving"

"JSON File1" -> DP_Klantinteractie: "realises"
"JSON File2" -> DP_RDI: "realises"

legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  business_color: "" {
    style: {
      fill: "#ffffaf"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  business_text: "Business" {
    shape: text
  }
  application_color: "" {
    style: {
      fill: "#afffff"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  application_text: "Application" {
    shape: text
  }
  technology_color: "" {
    style: {
      fill: "#afffaf"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  technology_text: "Technology" {
    shape: text
  }
}

classes: {
  *: {
    style: {
      shadow: true
    }
  }
  empty: {
    label: ""
    style: {
      fill: transparent
      stroke-width: 0
    }
  }
  verb: {
    style: {border-radius: 30}
  }
  noun: {
    style: {border-radius: 4}
  }
  artifact: {shape: page}
  business: {
    style: {
      fill: "#ffffaf"
    }
  }
  application: {
    style: {
      fill: "#afffff"
    }
  }
  technology: {
    style: {
      fill: "#afffaf"
    }
  }
}
----


1. De structuur van de dataset is gebaseerd op het _Begrippenmodel NBNL_ en het _Common Information Model_;
2. Aanlevering van de metergegevens, de aangeslotenegegevens en de klantinteractiegegevens geschiedt via JSON-bestanden;
3. Aanlevering van de dataset vanuit de netbeheerder geschiedt via JSON-bestand.

== Dataset

=== Volume, variety, veracity, velocity

[NOTE]
====
include::partial$four_v.adoc[]
====

In het centrale scenario zijn er twee verschillende dataproducten, _Klantinteractie_ en _RDI_, elk met hun eigen dataset en elke dataset heeft haar eigen kenmerken:

==== Dataset Klantinteractie

[cols="1, 3"]
|===
|Type |Beschrijving

|Volume
|Laag, < 100MB (ongecomprimeerd)

|Variety
|Gestructureerd

|Veracity
|Midden

|Velocity
|Laag
|===

==== Dataset RDI

[cols="1, 3"]
|===
|Type |Beschrijving

|Volume
|Laag, < 100MB (ongecomprimeerd)

|Variety
|Gestructureerd

|Veracity
|Hoog

|Velocity
|Laag
|===

== Voorwaarden

Dit dataproduct wordt als _gesloten data_ aangeboden, onder de grondslag _Wettelijke verplichting_.


== Beslissingen en aannames

[cols="1, 1"]
|===
|Type |Beschrijving

|Aanname
|Er is gekozen voor het centrale scenario

|Aanname
|EDSN heeft voldoende capaciteit om de benodigde gegevens op te vragen en te integreren 

|Aanname
|Het Aangeslotene Register kan de aangeslotenegegevens leveren (afhankelijkheid met de energieleverancier voor de klantcontactgegevens en de koppelbaarheid met de aansluitingsgegevens van de RNB)

|Aanname
|Aangeslotenegegevens, klantinteractiegegevens en metergegevens kunnen gekoppeld worden

|Aanname
|De aansluitingengegevens die de RNB's aanleveren bevatten alleen gegevens van aansluitingen met een  'ouderwetse terugdraaimeter'. Dus niet _verzenden en dan filteren_, maar _filteren en dan verzenden_. Idem voor klantinteractiegegevens en meteringegevens

|===
