= Rijksinspectie Data Infrastructuur (RDI)

Dit ontwerp beschrijft het beoogde gebruiksscenario van dataproduct _RDI_, alsmede haar achterliggende architectuur en de gemaakte keuzes. Het is geschreven vanuit het perspectief van de Regionale Netbeheerder (RNB), ook wel Distributiesysteembeheerder (DSB). Voor de leesbaarheid en voor de begripsvorming wordt soms ook een deel van de context ook beschreven. Deze valt echter _buiten scope_ en er kunnen geen rechten aan ontleend worden.

[NOTE]
====
include::partial$data_product.adoc[]
====

== Reikwijdte

Per 1 januari 2027 wordt de salderingsregeling afgeschaft. Klanten die op dat moment nog een 'ouderwetse terugdraaimeter' hebben kunnen dan nog altijd salderen en dat brengt rechtsongelijkheid. Om die reden worden de ouderwetse terugdraaimeters verboden en moet overal een meter geplaatst worden met een aparte registratie voor levering (afname) en teruglevering (invoeding). Hiervoor dienen de netbeheerders een aanbiedingsbrief te sturen. Indien dit niet resulteert in een plaatsing dan zal de Rijksinspectie Digitale Infrastructuur (RDI) overgaan tot handhaving. Daarvoor zal de RDI klantinteractiegegevens (procesdata) opvragen bij de RNB's: het dataproduct _RDI_.

== Functionele eisen

Het dataproduct moet voldoen aan functionele eisen; deze vertellen wie ("*Als rol*") welke data ("*Wil ik*") nodig heeft en waarom ("*Want*").

.Functionele eisen
[cols="1, 1, 1"]
|===
|Als rol |Wil ik |Want

|Regionale Netbeheerder (RNB)
|Een verzoek om klantinteractiegegevens krijgen met een sleutel waarmee ik de klant kan identificeren
|Het leveren van klantinteractiegegevens gaat op verzoek

|Rijksinspectie Digitale Infrastructuur (RDI)
|Klantinteractiegegevens van klanten waarvoor ik moet handhaven
|Deze gegevens heb ik nodig om een dossier op te bouwen

|===

== Dataservice

Er is gekozen voor een decentraal scenario waarbij de Rijksinspectie Digitale Infrastructuur (RDI) de Regionale Netbeheerds (RNB's) bevraagt _via_ de Gegevensuitwisselingsentiteit (GUE). 

=== Gebruiksscenario

.Gebruiksscenario 
[d2,svg,theme=4]
----

vars: {
  d2-config: {
    pad: 20
  }
}

Decentraal scenario: {
	shape: sequence_diagram

  RDI: "Rijksinspectie\nDigitale Infrastructuur\n(RDI)"
  "Gegevensuit-\nwisselentiteit\n(GUE)".style: {
    stroke: black
    stroke-dash: 1
  }
  RNB: "Regionale\nNetbeheerder\n(RNB)"
  
  RDI -> RNB: 1. Verzoek om klantinteractiegegevens
  RNB -> RDI: 2. Levering klantinteractiegegevens

}

----

1. De RDI stuurt, via de GUE, de sleutel van een klant naar de betreffende RNB met een verzoek om de klantinteractiegegevens van deze klant
2. De RNB stuurt, via de GUE, de klantinteractiegegevens van een klant

=== Architectuur

Vanuit architectuurperspectief zijn de volgende keuzes gemaakt:

.Architectuur
[d2,svg,theme=4]
----

vars: {
  d2-config: {
    pad: 20
  }
}

grid-rows: 5
grid-columns: 3

vertical-gap: 80
horizontal-gap: 160

1_1.class: empty
RNB.class: [noun; business]
RDI.class: [noun; business]

Extract.class: [verb; business]
Transform.class: [verb; business]
Load.class: [verb; business]

3_1.class: empty
Datamart: {
  label: Datamart\n(Meter\nKlantinteractie)
  class: [noun; application]
}
3_3.class: empty

DP_Klantcontact: {
  label: Dataproduct\nKlantcontact
  class: [noun; application]
}
"File gateway".class: [noun; application]
DP_Aangeslotene: {
  label: Dataproduct\nAangeslotene
  class: [noun; application]
}

"JSON File1": {
  label: JSON File\nKlantcontact
  class: [artifact; technology]
}
5_2.class: empty
"JSON File2": {
  label: JSON File\nAangeslotene
  class: [artifact; technology]
}

RNB -> Extract: "assigned to"
RNB -> Transform: "assigned to"
RNB -> Load: "assigned to"

Extract -> Transform: "triggers"
Transform -> Load: "triggers"
Load -> RDI: "serving"

Datamart -> Transform: "serving"
Datamart -> Load: "serving"

DP_Klantcontact -> Extract: "serving"
"File gateway" -> DP_Klantcontact: "accesses (read)"
"File gateway" -> DP_Aangeslotene: "accesses (read)"
DP_Aangeslotene -> Load: "serving"

"JSON File1" -> DP_Klantcontact: "realises"
"JSON File2" -> DP_Aangeslotene: "realises"

legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  business_color: "" {
    style: {
      fill: "#ffffaf"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  business_text: "Business" {
    shape: text
  }
  application_color: "" {
    style: {
      fill: "#afffff"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  application_text: "Application" {
    shape: text
  }
  technology_color: "" {
    style: {
      fill: "#afffaf"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  technology_text: "Technology" {
    shape: text
  }
}

classes: {
  *: {
    style: {
      shadow: true
    }
  }
  empty: {
    label: ""
    style: {
      fill: transparent
      stroke-width: 0
    }
  }
  verb: {
    style: {border-radius: 30}
  }
  noun: {
    style: {border-radius: 4}
  }
  artifact: {shape: page}
  business: {
    style: {
      fill: "#ffffaf"
    }
  }
  application: {
    style: {
      fill: "#afffff"
    }
  }
  technology: {
    style: {
      fill: "#afffaf"
    }
  }
}

----


1. De structuur van de dataset is gebaseerd op het _Begrippenmodel NBNL_ en het _Common Information Model_
2. Aanlevering van de klantcontactgegevens en de aangeslotenegegevens geschiedt met JSON-bestanden
3. Aanlevering van het meterwisseldossier vanuit de netbeheerder naar de RDI geschiedt met JSON-bestand

== Dataset

=== Volume, variety, veracity, velocity

[NOTE]
====
include::partial$four_v.adoc[]
====

In scenario zijn er twee verschillende dataproducten, _Klantcontact_ en _Aangeslotene_, elk met hun eigen dataset en elke dataset heeft haar eigen kenmerken:

==== Dataset _Klantcontact_

[cols="1, 3"]
|===
|Type |Beschrijving

|Volume
|Laag, < 100MB (ongecomprimeerd)

|Variety
|Gestructureerd

|Veracity
|Midden

|Velocity
|Laag
|===

==== Dataset _Aangeslotene_

[cols="1, 3"]
|===
|Type |Beschrijving

|Volume
|Laag, < 100MB (ongecomprimeerd)

|Variety
|Gestructureerd

|Veracity
|Hoog

|Velocity
|Laag
|===

== Voorwaarden

Dit dataproduct wordt als _gesloten data_ aangeboden, onder de grondslag _Wettelijke verplichting_.


== Beslissingen en aannames

[cols="1, 1"]
|===
|Type |Beschrijving

|Beslissing
|Er is gekozen voor het decentrale scenario waarbij elke RNB de benodigde gegevens bij de GUE opvraagt

|Aanname
|Het GUE regelt (eventuele) autorisatie en authenticatie

|Aanname
|Het Aangeslotene Register kan de aangeslotenegegevens leveren en deze kunnen gekoppeld worden

|Aanname
|De Energieleverancier kan de klantcontactgegevens leveren en deze kunnen gekoppeld worden

|Aanname
|Klantcontactgegevens, aangslotenegegevens, metergegevens en klantinteractiegegevens kunnen gekoppeld worden

|Aanname
|De RNB's kunnen de klanten met een 'ouderwetse terugdraaimeter' herkennen, zodat zij alleen van deze klanten gegevens opvragen

|Aanname
|Het betreft uitsluitend KV-klanten; GV-klanten hebben geen salderingsregeling (maar misschien wel een ouderwetse terugdraaimeter)

|Aanname
|Een RNB kan meerdere keren aan het GUE vragen om klantcontactgegevens. Zowel van dezelfde klant als van verschillende klanten

|Beslissing
|Het GUE levert de ontvangen gegevens (klantcontact en aangeslotene) ongewijzigd door aan de RNB

|Aanname
|De GUE is in staat de gevraagde gegevens tijdig te leveren

|Aanname
|De aangeslotene is de contactpersoon voor de aansluiting behorende bij de ouderwetse terugdraaimeter en kan (laten) beslissen of deze meter vervangen wordt door een slimme meter

|===
